from pathlib import Path
p=Path('index.html');s=p.read_text()
def rep(a,b,label):
 c=s.count(a)
 if c!=1: raise SystemExit(f'{label}:{c}')
 return s.replace(a,b,1)
old='''    function renderLearnPage() {
      openArchShell('Learn'); archDetailStack=[];
      const attendance=loadAttendanceData(), college=attendance.collegeLearningHours||0, learner=learnerLearningHours(), total=college+learner, required=totalLearningRequirement(), elapsed=courseProgressPercent();
      const targetNow=required!==null&&elapsed!==null?required*(elapsed/100):null;
      const catchup=targetNow===null?null:Math.max(0,targetNow-total);
      const label=inferredCourseMeta().courseType==='nvq'?'GLH':'OTJ';
      archDetailContent.innerHTML=`<div class="detail-metrics"><div class="detail-metric"><strong>${college.toFixed(1)}h</strong><span>college ${label}</span></div><div class="detail-metric"><strong>${learner.toFixed(1)}h</strong><span>learner-added ${label}</span></div><div class="detail-metric"><strong>${total.toFixed(1)}h</strong><span>total learning</span></div><div class="detail-metric"><strong>${targetNow===null?'--':`${targetNow.toFixed(1)}h`}</strong><span>expected by now</span></div></div><div class="detail-card"><strong>${required===null?'Learning requirement not yet supplied by Naxos':`${required.toFixed(1)} total ${label} hours required`}</strong>${catchup===null?'<p>Evia will calculate catch-up once the Naxos learning requirement and course dates are available.</p>':catchup>0?`<p>You need ${catchup.toFixed(1)} additional learning hours to reach the current course position.</p>`:'<p>You are currently on or ahead of the learning-hours position.</p>'}</div><button class="catchup-button" id="openLearnCatchup" type="button"><strong>Catch Up</strong><span>Check completed evidence for learning entries that may have been missed.</span></button>`;
    }'''
new='''    const OTJ_ACTIVITY_LIBRARY = [
      {id:'toolbox-talks',title:'Toolbox talks',description:'Toolbox talks or safety briefings that teach new KSB-relevant knowledge, controls or methods.',keywords:['toolbox','safety briefing','briefing']},
      {id:'tools',title:'Tools & equipment learning',description:'Learning to select, use, check, maintain or store tools and equipment correctly.',keywords:['tool','equipment','hand tool','power tool']},
      {id:'machinery',title:'Machinery & plant training',description:'Training or supervised learning on machinery, plant, powered equipment or safe operating methods.',keywords:['machinery','machine','plant','mixer','disc cutter']},
      {id:'manufacturer',title:'Manufacturer or product training',description:'Manufacturer demonstrations, product sessions or learning how new materials and systems are used.',keywords:['manufacturer','product training','demonstration','demo']},
      {id:'training-days',title:'Training days & courses',description:'Employer or provider training days and courses that develop new occupational KSBs.',keywords:['training day','training course','workshop']},
      {id:'shadowing',title:'Shadowing experienced workers',description:'Structured shadowing where you learn a new method, process, responsibility or occupational skill.',keywords:['shadow','shadowing']},
      {id:'mentoring',title:'Mentoring & coaching',description:'Mentoring or coaching that develops new occupational knowledge, skills or behaviours.',keywords:['mentor','mentoring','coach','coaching']},
      {id:'supervised-practice',title:'Supervised practice',description:'Practising a new or developing skill with guidance and feedback rather than routine productive work.',keywords:['supervised','practice','practise','feedback']},
      {id:'industry-visits',title:'Industry & site visits',description:'Visits used to learn about construction methods, systems, products, processes or another part of the industry.',keywords:['industry visit','site visit']},
      {id:'cpd-events',title:'CPD & apprentice events',description:'Relevant CPD sessions, trade events, apprentice events, seminars or technical presentations.',keywords:['cpd','seminar','apprentice event','trade event']},
      {id:'online-learning',title:'Online learning & webinars',description:'Structured online learning, webinars or tutorials that develop occupational KSBs.',keywords:['webinar','online learning','online course','tutorial']},
      {id:'drawings-specs',title:'Drawings, specifications & technical information',description:'Learning how to read, interpret or use drawings, specifications, technical information and work instructions.',keywords:['drawing','specification','technical information']},
      {id:'planning-estimating',title:'Planning, estimating & digital tools',description:'Learning planning, estimating, measurement, digital design, modelling or construction software skills.',keywords:['planning','estimate','estimating','digital','software','modelling','modeling']},
      {id:'quality',title:'Quality checks & inspection',description:'Learning new quality-control, measurement, tolerance, inspection, testing or defect-prevention methods.',keywords:['quality','inspection','tolerance','testing']},
      {id:'sustainability',title:'Environment & sustainability',description:'Learning about waste, recycling, efficient resources, environmental controls or sustainable construction.',keywords:['sustainability','environment','recycling','waste']},
      {id:'materials-methods',title:'New materials & construction methods',description:'Learning about unfamiliar materials, products, installation methods or modern construction techniques.',keywords:['material','new method','construction method']},
      {id:'health-safety',title:'Health, safety & wellbeing training',description:'Training that teaches new relevant health, safety, wellbeing, PPE, RPE, RAMS or hazard-control knowledge.',keywords:['health and safety','health & safety','ppe','rpe','rams','risk assessment','wellbeing']},
      {id:'communication-team',title:'Communication & team development',description:'Structured learning that develops occupational communication, teamwork, inclusion or coordination behaviours.',keywords:['communication','teamwork','team working','inclusion','coordination']},
      {id:'study-revision',title:'Occupational study & revision',description:'Study, revision or assignment work that develops the occupational KSBs required by the apprenticeship.',keywords:['study','revision','assignment','research']},
      {id:'new-responsibilities',title:'Preparing for new responsibilities',description:'Structured learning before taking on a new occupational task, process or responsibility.',keywords:['new responsibility','new task','preparation']}
    ];
    function learningEntryMatchesOtjIdea(entry,idea){if(cleanText(entry?.activityType)===idea.id)return true;const text=`${entry?.text||''} ${entry?.evidenceLabel||''}`.toLowerCase();return idea.keywords.some(keyword=>text.includes(keyword))}
    function uncoveredOtjIdeas(){return OTJ_ACTIVITY_LIBRARY.filter(idea=>!learningEntries.some(entry=>learningEntryMatchesOtjIdea(entry,idea)))}
    function renderOtjIdeasPage(){const uncovered=uncoveredOtjIdeas(),ids=new Set(uncovered.map(x=>x.id)),priority=uncovered.slice(0,8);archDetailContent.innerHTML=`<div class="detail-card"><strong>Other off-the-job learning to consider</strong><p>College learning is tracked separately, so Evia does not suggest normal college days here. Only record an activity when it was active learning that developed new occupational KSBs during working hours.</p><p class="detail-muted">Routine productive work, progress reviews and standalone English or maths qualifications are not suggested as OTJ here.</p></div><div class="detail-section-heading"><strong>Areas not recorded yet</strong><span>${uncovered.length} of ${OTJ_ACTIVITY_LIBRARY.length}</span></div><div class="otj-ideas">${priority.length?priority.map(idea=>`<div class="otj-idea uncovered"><span class="otj-idea-badge">Not recorded yet</span><strong>${escapeDetailHtml(idea.title)}</strong><span>${escapeDetailHtml(idea.description)}</span></div>`).join(''):'<div class="detail-card"><strong>Good coverage</strong><p>Your Learn entries already mention all of Evia’s OTJ idea areas.</p></div>'}</div><div class="detail-section-heading"><strong>Full OTJ idea list</strong><span>College days excluded</span></div><div class="otj-ideas">${OTJ_ACTIVITY_LIBRARY.map(idea=>`<div class="otj-idea${ids.has(idea.id)?' uncovered':''}">${ids.has(idea.id)?'<span class="otj-idea-badge">Gap to consider</span>':''}<strong>${escapeDetailHtml(idea.title)}</strong><span>${escapeDetailHtml(idea.description)}</span></div>`).join('')}</div>`}
    function renderLearnPage(){openArchShell('Learn');archDetailStack=[];const attendance=loadAttendanceData(),college=attendance.collegeLearningHours||0,learner=learnerLearningHours(),total=college+learner,required=totalLearningRequirement(),elapsed=courseProgressPercent();const targetNow=required!==null&&elapsed!==null?required*(elapsed/100):null,catchup=targetNow===null?null:Math.max(0,targetNow-total),label=inferredCourseMeta().courseType==='nvq'?'GLH':'OTJ',uncovered=uncoveredOtjIdeas();archDetailContent.innerHTML=`<div class="detail-card"><strong>${label} learning position</strong><p>${required===null?'Evia is waiting for the course learning-hours requirement from Naxos.':`${required.toFixed(1)} total ${label} hours are required for this course.`}</p></div><div class="detail-metrics"><div class="detail-metric"><strong>${college.toFixed(1)}h</strong><span>college ${label}</span></div><div class="detail-metric"><strong>${learner.toFixed(1)}h</strong><span>learner-added ${label}</span></div><div class="detail-metric"><strong>${total.toFixed(1)}h</strong><span>total learning</span></div><div class="detail-metric"><strong>${targetNow===null?'--':`${targetNow.toFixed(1)}h`}</strong><span>expected by now</span></div></div><div class="detail-card"><strong>${catchup===null?'Catch-up position not available yet':catchup>0?`${catchup.toFixed(1)}h to catch up`:'On or ahead of target'}</strong>${catchup===null?'<p>Evia will calculate catch-up once the Naxos learning requirement and course dates are available.</p>':catchup>0?`<p>You need ${catchup.toFixed(1)} additional learning hours to reach the current course position.</p>`:'<p>Your recorded learning hours are currently on or ahead of the expected course position.</p>'}</div><button class="catchup-button" id="openLearnCatchup" type="button"><strong>Catch Up from evidence</strong><span>Check completed evidence for Learn entries that may have been missed.</span></button><button class="catchup-button" id="openOtjIdeas" type="button"><strong>Explore OTJ ideas</strong><span>${uncovered.length} learning area${uncovered.length===1?'':'s'} not yet mentioned in your Learn entries. College days are excluded.</span></button>`}'''
s=rep(old,new,'learn')
old2='''    async function updateArchBars(){
      const elapsed=courseProgressPercent();timeArchValue.textContent=elapsed===null?'--':`${Math.round(elapsed)}%`;
      if(courseItems===placeholderCourse){courseArchValue.textContent='--'}else{
        try{const leaves=courseLeaves(),entries=await getPortfolioEntries(),covered=new Set(entries.map(entry=>Array.isArray(entry.path)?entry.path.join('||'):'').filter(Boolean)),count=leaves.filter(leaf=>covered.has(leaf.path.join('||'))).length;courseArchValue.textContent=leaves.length?`${Math.round((count/leaves.length)*100)}%`:'--'}catch(error){courseArchValue.textContent='--'}
      }
      const attendance=combinedAttendancePercent();attendanceArchValue.textContent=attendance===null?'--':`${Math.max(0,Math.min(100,Math.round(attendance)))}%`;
      const required=totalLearningRequirement(), college=loadAttendanceData().collegeLearningHours||0, learner=learnerLearningHours(), total=college+learner;
      learnArchValue.textContent=required?`${Math.min(100,Math.round((total/required)*100))}%`:String(learningEntries.length||0);
    }'''
new2='''    function setArchProgress(archId,value){const arch=document.getElementById(archId),n=Number(value),ready=value!==null&&value!==undefined&&Number.isFinite(n);if(!arch)return;arch.style.setProperty('--arch-progress',String(ready?Math.max(0,Math.min(100,n)):0));arch.classList.toggle('progress-ready',ready)}
    async function updateArchBars(){const elapsed=courseProgressPercent();timeArchValue.textContent=elapsed===null?'--':`${Math.round(elapsed)}%`;setArchProgress('timeArch',elapsed);let coursePercent=null;if(courseItems===placeholderCourse){courseArchValue.textContent='--'}else{try{const leaves=courseLeaves(),entries=await getPortfolioEntries(),covered=new Set(entries.map(entry=>Array.isArray(entry.path)?entry.path.join('||'):'').filter(Boolean)),count=leaves.filter(leaf=>covered.has(leaf.path.join('||'))).length;coursePercent=leaves.length?(count/leaves.length)*100:null;courseArchValue.textContent=coursePercent===null?'--':`${Math.round(coursePercent)}%`}catch(error){courseArchValue.textContent='--';coursePercent=null}}setArchProgress('courseArch',coursePercent);const attendance=combinedAttendancePercent();attendanceArchValue.textContent=attendance===null?'--':`${Math.max(0,Math.min(100,Math.round(attendance)))}%`;setArchProgress('attendanceArch',attendance);const required=totalLearningRequirement(),college=loadAttendanceData().collegeLearningHours||0,learner=learnerLearningHours(),total=college+learner,learnPercent=required?Math.min(100,(total/required)*100):null;learnArchValue.textContent=learnPercent!==null?`${Math.round(learnPercent)}%`:String(learningEntries.length||0);setArchProgress('learnArch',learnPercent)}'''
s=rep(old2,new2,'arches')
p.write_text(s)
