const C={
bricklayer:{name:"Bricklayer",std:"ST0095 v1.2",u:[
["Mixing mortar",["S14|Gauge and hand mix mortar to ratio.","K20|Mixing Mortar: Ratios, silos, pre-mixed, gauging, hand mixing and mechanical mixing.","S1|Comply with health and safety regulations, standards, and guidance.","K1|signage, Safety signage.","S6|Estimate and select required resources: For example, the quantity of bricks and blocks, mortar, wall ties and insulation.","K12|Simple resource estimation techniques: Quantity of bricks and blocks, amount of mortar, quantity of wall ties, DPCs, cavity trays and lintels.","K11|Basic principles of digital design and modelling systems.","B1|Put health, safety and wellbeing first."]],
["Jointing Styles",["S12|Apply joint finishes: For example, half round, flush, weather struck and recessed.","K17|Joint finishes: Half round, flush, weather struck and recessed.","S2|Identify and use personal protective equipment (PPE).","K2|Safety control equipment and how to use personal protective equipment (PPE).","S17|Protect materials and finished work.","K25|Methods of protecting materials and work: Frost, water and construction damage.","K27|Principles of good team working.","B6|Team-focus to meet team goals including, considering the wider build team."]],
["Repair brick walling",["S16|Carry out a simple repair: For example, replacing damaged bricks.","K24|Defects and repair: Construction defects and repair methods.","S1|Comply with health and safety regulations, standards, and guidance.","K1|Asbestos awareness.","S7|Prepare and maintain a safe working area.","K3|Safe systems of work: Site inductions, toolbox talks, risk assessments, method statements and hazard identification in the work area.","S20|Applies team working principles to their own and the wider build team.","B2|Consider the environment when using resources and carrying out processes."]],
["Basic Brick wall",["S13|Set out and construct a simple brick solid wall with capping.","K16|Brick solid wall setting out, construction and capping methods.","S2|Identify and use personal protective equipment (PPE).","K1|Awareness of health and safety regulations, standards, and guidance and impact on role.","S8|Select and use hand tools.","S9|Maintain and store hand tools.","K13|Hand tool use, maintenance and storage: Levels, measures, hammers, bolsters, brick hammers, trowels, brick jointer, line blocks and pins, scutch, chariot and brick clamps.","K6|Principles of building: Foundations, roofs, walls, cavity step trays, floors, utilities and services, insulation, fire, moisture and air protection, damp proof courses, the use of brick ties and quality of materials.","B1|Put health, safety and wellbeing first."]],
["Set out solid walling",["S13|Set out and construct a simple brick solid wall with capping.","K16|Brick solid wall setting out, construction and capping methods.","S5|Read and interpret information from drawings and specifications.","K1|Situational awareness. Slips, trips, and falls.","S18|Verbally communicate with others, applying construction terminology.","K26|Verbal communication techniques and construction terminology.","K18|Principles of basic decorative walling and piers: projecting and contrasting brick, isolated and attached pier, banding.","B3|Take ownership of given work."]],
["Build solid walling",["S13|Set out and construct a simple brick solid wall with capping.","K16|Brick solid wall setting out, construction and capping methods.","S5|Read and interpret information from drawings and specifications.","K10|Methods of interpreting and extracting relevant information from drawings and specifications.","S3|Comply with environmental and sustainability regulations, standards, and guidance. Segregate resources for reuse, recycling and disposal.","K4|Impact of the sector on the environment: Efficient use of resources. Recycling, reuse, surface water contamination and safe disposal of waste.","K15|Bond types: English bond, flemish bond, garden wall bonds and broken bond.","B2|Consider the environment when using resources and carrying out processes."]],
["Set out Cavity Walling",["S10|Set out brick and block cavity wall to given tolerances, including an opening. damp proof courses (DPCs), cavity trays, weep holes.","K21|Cavity wall setting out techniques: Bricks and blocks, openings and levels, use of profiles, gauge rods and squares. damp proof courses (DPCs), cavity trays, weep holes.","S1|Comply with health and safety regulations, standards, and guidance.","K1|Control of Substances Hazardous to Health (CoSHH). Provision and use of work equipment regulations (PUWER) and Electrical safety. Health and Safety at Work Act. Manual handling","S6|Estimate and select required resources: For example, the quantity of bricks and blocks, mortar, wall ties and insulation.","K12|Simple resource estimation techniques: Quantity of bricks and blocks, amount of mortar, quantity of wall ties, DPCs, cavity trays and lintels.","K8|Materials and their characteristics: Bricks and blocks, efflorescence, mortar, damp proof courses (DPC), wall ties, plasticisers, concrete and steel lintels, Rolled Steel Joist (RSJ), fire stopping, insulation, cement and building sand.","B5|Seek learning and development opportunities."]],
["Construct Cavity Walling",["S11|Construct a stretcher bond brick and block cavity wall with return and opening to given tolerances, insulation, fire stopping.","K22|Cavity wall construction using stretcher bond brick and block walling, forming openings, insulation, fire stopping.","S5|Read and interpret information from drawings and specifications.","K1|Fire safety, fire extinguishers","S21|Identifies well-being support available to self and others.","K31|Well-being: Mental and physical health considerations in self and others and how to access support.","K5|The importance and considerations of the environment and sustainability: Thermal qualities, airtightness and ventilation in buildings.","B5|Seek learning and development opportunities."]],
["Cavity opening",["S11|brick and edge sill, closure around opening, including installing a lintel with soldiers","K22|closing cavities. selection and placement of wall ties, lintels","S4|Comply with industry regulations, standards, and guidance.","K7|Standards and regulations associated with bricklaying activities: British standards, building regulations and warranty provider standards.","S19|Follow equity, diversity and inclusion guidance.","K28|Inclusion, equity and diversity in the workplace.","K19|Principles of the use of expansion joints.","K9|Modern methods of construction: Rapid build technology, precast components, corner profiles, alternative frame and cladding systems, masonry support systems.","B4|Contribute to an inclusive and diverse culture."]],
["Gable end/Raked wall",["S22|Construct a brick wall with raking cut. For example, gable end wall or garden wall with raking cut.","K30|Brick walls with raking cut: Setting out and construction techniques.","S2|Identify and use personal protective equipment (PPE).","K1|Working in confined spaces. Working at height.","S15|Measure and cut bricks and blocks using hand tools, to given tolerances.","K29|Methods of cutting bricks and blocks using hand tools.","K14|Power tool use and limitations: Disc cutters, mixers and drills.","B3|Take ownership of given work."]]
]},
site:{name:"Site Carpenter",std:"ST0264 v1.4",u:[
["Structural carcassing",["S14|Site carpenter: Apply first fix techniques and practices for: 1. structural carcassing (load bearing studwork)","K27|Site carpentry: First fixing installation techniques: Structural carcassing (load bearing studwork)","S1|Comply with health and safety regulations, standards, and guidance.","K1|Awareness of health and safety regulations, standards, and guidance and impact on role.","S10|Select, use and store power tools.","K17|Power tools use and storage methods and techniques: Portable circular saws, drills, saws, planers, routers, sanders, multi-functional tools and nail guns.","K9|Materials and their characteristics of home grown and imported timber and timber-based products","B1|Put health, safety and wellbeing first."]],
["Timber/metal partition walls",["S14|Site carpenter: Apply first fix techniques and practices for: 2. straight timber or metal partition walls","K27|Site carpentry: First fixing installation techniques: metal and timber stud partitions.","S19|Site carpenter: Use and store laser levels for example cross line laser.","K29|Site carpentry: Types, use, calibration and storage of laser levels.","S16|Site carpenter: Size timber from sizing tables.","K23|Site Carpenter: Timber sizing tables purpose and use.","K5|Principles of building and modern methods of construction","B4|Seek learning and development opportunities."]],
["Floor joists (and coverings)",["S14|Site carpenter: Apply first fix techniques and practices for: 3. floor joists, 4. floor joist coverings","K27|Site carpentry: First fixing installation techniques: floor joists and coverings","S2|Identify and use safety control equipment, for example, RPE, dust suppression, PPE and LEV.","K1|Control of Substances Hazardous to Health (CoSHH).Provision of work equipment regulations (PUWER) and Electrical safety. Health and Safety at Work Act. Manual handling","S15|Site carpenter: Install structural fixings.","K22|Site carpentry: Structural fixtures and timber sizing in site carpentry, how to use sizing tables.","K10|Timber decay and repair methods","B2|Consider the environment when using resources and carrying out processes."]],
["Straight flights of stairs",["S14|Site carpenter: Apply first fix techniques and practices for: 5. straight flights of stairs.","K27|Site carpentry: First fixing installation techniques: straight flights of stairs","S1|Comply with health and safety regulations, standards, and guidance.","K1|Situational awareness. Slips, trips, and falls.","S6|Interpret and use information from drawings and specifications.","K8|Methods of interpreting and extracting relevant information from drawings and specifications.","K6|Basic principles of digital design and modelling systems","B1|Put health, safety and wellbeing first."]],
["Service encasement",["S17|Site carpenter: Apply site second fix techniques and practices for: 1. service encasement","K28|Site carpentry: Second fix installation techniques: Service encasement","S2|Identify and use safety control equipment, for example, RPE, dust suppression, PPE and LEV.","K1|Fire safety, fire extinguishers","S9|Select, use and store hand tools.","K14|Hand tool use and storage methods and techniques: Chisels, planes, hand saws, hammers, squares, tri-square, bevels, marking and mortise gauges, spirit levels.","S13|Identifies well-being support available to self and others.","B3|Contribute to an inclusive and diverse culture."]],
["Cladding",["S17|Site carpenter: Apply site second fix techniques and practices for: 2. cladding","K28|Site carpentry: Second fix installation techniques: cladding","S1|Comply with health and safety regulations, standards, and guidance.","K1|Asbestos awareness.","S5|Prepare and maintain a safe working area.","K3|Safe systems of work: Site inductions, tool box talks, risk assessments, method statements and hazard identification in the work area.","K20|Well-being: Mental and physical health considerations in self and others and how to access support.","B1|Put health, safety and wellbeing first."]],
["Wall and floor units",["S17|Site carpenter: Apply site second fix techniques and practices for: 3. wall and floor units and fitments","K28|Site carpentry: Second fix installation techniques: wall and floor units and fitments","S3|Comply with environmental and sustainability regulations, standards, and guidance. Segregate resources for reuse, recycling and disposal.","K4|Impact of the sector on the environment: Efficient use of resources. Recycling, reuse, safe disposal of waste and sustainable forestry.","S12|Produce jigs.","K16|Jig production techniques.","K18|Principles of good team working","B5|Team-focus to meet team goals including, considering the wider build team."]],
["Handrails and spindles",["S17|Site carpenter: Apply site second fix techniques and practices for: 4. handrails and spindles to straight flights of stairs","K28|Site carpentry: Second fix installation techniques: handrails and spindles to straight flights of stairs","S1|Comply with health and safety regulations, standards, and guidance.","K1|signage, Safety signage.","S8|Verbally communicate with others, applying construction terminology.","K13|Verbal communication techniques and construction terminology.","K14|Hand tool use and storage methods and techniques: Chisels, planes, hand saws, hammers, squares, tri-square, bevels, marking and mortise gauges, spirit levels.","B4|Seek learning and development opportunities."]],
["Internal and external doors",["S17|Site carpenter: Apply site second fix techniques and practices for: 5. internal and external doors","K28|Site carpentry: Second fix installation techniques: doors","S20|Site carpenter: Form connections, for example, using joints, nails, screws, bolts and adhesive.","K11|Carpentry and joinery products and purpose: Mastics, preservatives, wood fillers, plastics and ironmongery.","S11|Maintain and sharpen hand tools.","K15|Hand tool maintenance and sharpening techniques.","K8|Methods of interpreting and extracting relevant information from drawings and specifications.","B1|Put health, safety and wellbeing first."]],
["Skirting boards and architrave",["S17|Site carpenter: Apply site second fix techniques and practices for: 6. skirting boards and architrave","K28|Site carpentry: Second fix installation techniques: mouldings (architrave and skirting board).","S2|Identify and use safety control equipment, for example, RPE, dust suppression, PPE and LEV.","K2|Safety control equipment and how to use personal protective equipment (PPE) respiratory protective equipment (RPE) and local exhaust ventilation (LEV).","S22|Site carpenter: Carrying out splicing and scribing techniques.","K24|Site carpentry: Timber splicing and scribing techniques.","K40|Employment types, small business start up principles and tax","B2|Consider the environment when using resources and carrying out processes."]],
["Window boards",["S17|Site carpenter: Apply site second fix techniques and practices for: 7. window boards.","K28|Site carpentry: Second fix installation techniques: window boards","S4|Comply with industry regulations, standards, and guidance.","K7|Standards and regulations associated with carpentry activities: British standards, building regulations and warranty provider standards.","S21|Site carpenter: Apply measuring, marking out, cutting (square and angled), mitring, hinging and recessing techniques.","K21|Site carpentry techniques: Measuring, marking out, fitting, cutting (straight and angled) and mitring.","K19|Inclusion, equity and diversity in the workplace","B3|Contribute to an inclusive and diverse culture."]],
["Roofs and loft hatch",["S18|Site carpenter: Apply site carpenter techniques and practices to construction of rafter roofs, including trussed (prefabricated) and traditional (built on site) including the construction of verge, eaves and fitting loft access.","K25|Site carpentry: Straight roof installation techniques: Basic rafter trussed (prefabricated) and traditional cut roof (built on site).","S1|Comply with health and safety regulations, standards, and guidance.","K1|Working in confined spaces. Working at height.","S7|Estimate required materials and produce a cutting list.","K12|Basic material estimation techniques, calculating lengths of timber, fixing requirements and a cutting list production methods.","K26|Flat roofs: Warm and cold flat roofs including firings and coverings","B5|Team-focus to meet team goals including, considering the wider build team."]]
]},
joiner:{name:"Architectural Joiner",std:"ST0264 v1.4",u:[
["Basic woodworking joints",["S24|Architectural joiner: Produce basic woodworking joints including dovetail, bridal, mortise and tenon and halving.","K33|Architectural joiner: Timber joints, types and production techniques: Dovetails, mortise and tenon, bridals and halvings.","S1|Comply with health and safety regulations, standards, and guidance.","K1|Awareness of health and safety regulations, standards, and guidance and impact on role.","S25|Architectural joiner: Form connections using dowels, biscuit, staples and adhesives.","K35|Architectural joiner: Connection methods in joinery: Dowels, biscuit, staples and adhesives.","K9|Materials and their characteristics of home grown and imported timber and timber-based products","B1|Put health, safety and wellbeing first."]],
["Timber Window",["S26|Architectural joiner: Apply techniques and practices to the manufacture and assembly of a timber window with casement including glazing rebates and associated ironmongery.","K34|Architectural joiner: Manufacture and assembly techniques for standard right angled timber windows.","S2|Identify and use safety control equipment, for example, RPE, dust suppression, PPE and LEV.","K1|Asbestos awareness.","S6|Interpret and use information from drawings and specifications.","K8|Methods of interpreting and extracting relevant information from drawings and specifications.","K6|Basic principles of digital design and modelling systems","B2|Consider the environment when using resources and carrying out processes."]],
["Straight staircases",["S27|Architectural joiner: Apply manufacture and assembly techniques for first fix products: 1. straight staircases","K36|Architectural joiner: Manufacture and assembly techniques for timber first fix products: 1. straight staircases","S1|Comply with health and safety regulations, standards, and guidance.","K1|Working in confined spaces. Working at height.","S7|Estimate required materials and produce a cutting list.","K12|Basic material estimation techniques, calculating lengths of timber, fixing requirements and a cutting list production methods.","K13|Verbal communication techniques and construction terminology","S8|Verbally communicate with others, applying construction terminology.","B3|Contribute to an inclusive and diverse culture."]],
["Door frames and linings",["S27|Architectural joiner: Apply manufacture and assembly techniques for first fix products: 2. door frames and linings.","K36|Architectural joiner: Manufacture and assembly techniques for timber first fix products: 2. door frames and linings.","S2|Identify and use safety control equipment, for example, RPE, dust suppression, PPE and LEV.","K1|signage, Safety signage.","S11|Maintain and sharpen hand tools.","K15|Hand tool maintenance and sharpening techniques.","K10|Timber decay and repair methods","B4|Seek learning and development opportunities."]],
["Timber doors",["S28|Architectural joiner: Apply manufacture and assembly techniques for second fix products: 1. timber doors","K37|Architectural joiner: Apply manufacture and assembly techniques for second fix products: 1. timber doors","S1|Comply with health and safety regulations, standards, and guidance.","K1|Control of Substances Hazardous to Health (CoSHH).Provision of work equipment regulations (PUWER) and Electrical safety. Health and Safety at Work Act. Manual handling","S10|Select, use and store power tools.","K17|Power tools use and storage methods and techniques: Portable circular saws, drills, saws, planers, routers, sanders, multi-functional tools and nail guns.","K30|Requirements of fire door assemblies","B5|Team-focus to meet team goals including, considering the wider build team."]],
["Wall and floor units",["S28|Architectural joiner: Apply manufacture and assembly techniques for second fix products:2. wall and floor units","K37|Architectural joiner: Apply manufacture and assembly techniques for second fix products:2. wall and floor units","S2|Identify and use safety control equipment, for example, RPE, dust suppression, PPE and LEV.","K2|Safety control equipment and how to use personal protective equipment (PPE) respiratory protective equipment (RPE) and local exhaust ventilation (LEV).","S23|Architectural joiner: Produce setting out details, including setting rods, and mark out for timber products.","K32|Architectural joiner: Setting out and marking out techniques for joinery product manufacture and potential effects of marking out errors.","K40|Employment types, small business start up principles and tax","B1|Put health, safety and wellbeing first."]],
["Timber mouldings",["S28|Architectural joiner: Apply manufacture and assembly techniques for second fix products: 3. timber mouldings","K37|Architectural joiner: Manufacture and assembly techniques for second fix timber products: 3. timber mouldings.","S3|Comply with environmental and sustainability regulations, standards, and guidance. Segregate resources for reuse, recycling and disposal.","K4|Impact of the sector on the environment: Efficient use of resources. Recycling, reuse, safe disposal of waste and sustainable forestry.","S13|Identifies well-being support available to self and others.","K20|Well-being: Mental and physical health considerations in self and others and how to access support.","K38|Finishing techniques for manufactured timber products","B2|Consider the environment when using resources and carrying out processes."]],
["Staircase spindles and balustrades",["S28|Architectural joiner: Apply manufacture and assembly techniques for second fix products: 4. staircase spindles and balustrades.","K37|Architectural joiner: Manufacture and assembly techniques for second fix timber products: 4. staircase spindles and balustrades.","S1|Comply with health and safety regulations, standards, and guidance.","K1|Situational awareness. Slips, trips, and falls.","S12|Produce jigs.","K16|Jig production techniques.","K18|Principles of good team working.","B3|Contribute to an inclusive and diverse culture."]],
["Ironmongery",["S29|Architectural joiner: Fit ironmongery including door locks, door handles, door hinges, latches and draw runners.","K39|Architectural joiner: Ironmongery installation techniques.","S4|Comply with industry regulations, standards, and guidance.","K7|Standards and regulations associated with carpentry activities: British standards, building regulations and warranty provider standards.","S9|Select, use and store hand tools.","K14|Hand tool use and storage methods and techniques: Chisels, planes, hand saws, hammers, squares, tri-square, bevels, marking and mortise gauges, spirit levels.","K19|Inclusion, equity and diversity in the workplace","B4|Seek learning and development opportunities."]],
["Fixed Machinery",["S30|Architectural joiner: Inspect, prepare and operate fixed machinery.","K31|Architectural joiner: Safe use of fixed machinery, inspection, preparation and operation techniques: Crosscut saw, band saw, planer and thicknesser and mortiser.","S2|Identify and use safety control equipment, for example, RPE, dust suppression, PPE and LEV.","K1|Fire safety, fire extinguishers","S5|Prepare and maintain a safe working area.","K3|Safe systems of work: Site inductions, tool box talks, risk assessments, method statements and hazard identification in the work area.","K5|Principles of building and modern methods of construction","B5|Team-focus to meet team goals including, considering the wider build team."]]
]}};
const esc=s=>String(s??"").replace(/[&<>"']/g,x=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[x]));
let course=localStorage.getItem("evia7-course")||"bricklayer", screen="learning", unit=-1, photos=[], evidence=JSON.parse(localStorage.getItem("evia7-evidence")||"[]"), hours=JSON.parse(localStorage.getItem("evia7-hours")||"[]"), otjBatches=JSON.parse(localStorage.getItem("evia7-otj-batches")||"[]");
hours=hours.map((x,i)=>Object.assign({id:"legacy-"+i,createdAt:x.createdAt||Date.parse(x.d)||Date.now(),savedAt:x.savedAt||x.d||""},x));
const $=s=>document.querySelector(s), data=()=>C[course], code=x=>x.split("|")[0], text=x=>x.split("|").slice(1).join("|");
function persist(){localStorage.setItem("evia7-course",course);localStorage.setItem("evia7-evidence",JSON.stringify(evidence));localStorage.setItem("evia7-hours",JSON.stringify(hours));localStorage.setItem("evia7-otj-batches",JSON.stringify(otjBatches))}
function picker(){return '<div class="course-picker">'+Object.keys(C).map(k=>'<button class="pill '+(k===course?"active":"")+'" data-c="'+k+'">'+esc(C[k].name)+'</button>').join("")+'</div>'}
function nav(s){screen=function formatDateTime(ts){
 const d=new Date(ts);
 return d.toLocaleString("en-GB",{day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit"});
}
function otjEntriesForBatch(batch){
 if(!batch)return[];
 const ids=new Set(batch.entryIds||[]);
 return hours.filter(x=>ids.has(x.id));
}
function buildOTJPrintWindow(entries,title,downloadedAt){
 const p=JSON.parse(localStorage.getItem("evia7-profile")||"{}");
 const learner=p.name||"Apprentice";
 const total=entries.reduce((a,x)=>a+Number(x.n||0),0);
 const w=window.open("","_blank");
 if(!w){alert("Please allow pop-ups to download your off-the-job evidence PDF.");return false}
 w.document.write('<!doctype html><html lang="en"><head><meta charset="utf-8"><title>'+esc(title)+'</title><style>'+
 '@page{size:A4;margin:15mm}*{box-sizing:border-box}body{margin:0;color:#172033;font:10.5pt -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;line-height:1.45}.header{border-bottom:2px solid #e6b800;padding-bottom:14px;margin-bottom:18px}.eyebrow{font-size:8.5pt;letter-spacing:.12em;color:#667085;font-weight:700}.header h1{font-size:22pt;margin:4px 0 12px}.details{display:grid;grid-template-columns:1fr 1fr;gap:5px;color:#475467}.summary{background:#fff7d6;border:1px solid #f1df91;border-radius:10px;padding:10px;margin-bottom:16px}.entry{border:1px solid #e4e7ec;border-radius:11px;padding:13px;margin-bottom:10px;break-inside:avoid;page-break-inside:avoid}.entry-date{font-size:8.5pt;color:#667085;font-weight:700;letter-spacing:.05em}.entry-hours{font-size:15pt;font-weight:800;margin:3px 0}.entry-description{white-space:pre-wrap;color:#344054}.footer{margin-top:18px;padding-top:10px;border-top:1px solid #eaecf0;color:#667085;font-size:8.5pt}@media print{body{print-color-adjust:exact;-webkit-print-color-adjust:exact}}</style></head><body>'+
 '<header class="header"><div class="eyebrow">EVIA · OFF-THE-JOB LEARNING EVIDENCE</div><h1>'+esc(learner)+'</h1><div class="details">'+
 '<span><strong>Course:</strong> '+esc(data().name)+'</span><span><strong>Standard:</strong> '+esc(data().std)+'</span>'+
 (p.start?'<span><strong>Apprenticeship start:</strong> '+esc(p.start)+'</span>':"")+
 (p.end?'<span><strong>Apprenticeship end:</strong> '+esc(p.end)+'</span>':"")+
 '<span><strong>PDF generated:</strong> '+esc(formatDateTime(downloadedAt))+'</span></div></header>'+
 '<div class="summary"><strong>'+total.toFixed(2)+' hours</strong> across '+entries.length+' learning entries included in this download.</div>'+
 entries.slice().sort((a,b)=>Number(a.createdAt)-Number(b.createdAt)).map(x=>'<article class="entry"><div class="entry-date">'+esc(x.savedAt||formatDateTime(x.createdAt))+'</div><div class="entry-hours">'+esc(Number(x.n).toFixed(2))+' hours</div><div class="entry-description">'+esc(x.description||"No description recorded.")+'</div></article>').join("")+
 '<div class="footer">This document contains the off-the-job learning entries included at the time of this download. The next Evia OTJ download will contain new entries recorded after this download.</div>'+
 '</body></html>');
 w.document.close();w.focus();setTimeout(()=>w.print(),250);return true;
}
function downloadOTJPDF(mode){
 const now=Date.now();
 let entries=[],batch=null;
 if(mode==="last"){
   batch=otjBatches[otjBatches.length-1];
   entries=otjEntriesForBatch(batch);
   if(!entries.length){alert("There is no saved OTJ PDF to download again.");return}
   buildOTJPrintWindow(entries,"Evia OTJ evidence · "+(batch.downloadedAt?formatDateTime(batch.downloadedAt):""),batch.downloadedAt||now);
   return;
 }
 const lastBatch=otjBatches[otjBatches.length-1];
 const lastCutoff=lastBatch?Number(lastBatch.cutoff):0;
 entries=hours.filter(x=>Number(x.createdAt)>lastCutoff);
 if(!entries.length){alert("There is no new off-the-job learning to include in a new PDF. Add more learning entries first.");return}
 batch={id:"otj-"+now+"-"+Math.random().toString(36).slice(2,8),downloadedAt:now,cutoff:now,entryIds:entries.map(x=>x.id)};
 if(!buildOTJPrintWindow(entries,"Evia OTJ evidence · "+formatDateTime(now),now))return;
 otjBatches.push(batch);persist();learning();
}
function learning(){
 $("#page-title").textContent="Learning";
 const total=hours.reduce((a,x)=>a+Number(x.n),0);
 const lastBatch=otjBatches[otjBatches.length-1];
 const pending=hours.filter(x=>Number(x.createdAt)>Number(lastBatch?lastBatch.cutoff:0)).length;
 $("#screen").innerHTML='<div class="card"><div class="section-title">Off-the-job learning</div><h2>Record learning from site</h2><p>Record the hours you complete and describe what you learned or did.</p><div class="learning-input" style="margin-top:14px"><input id="hrs" type="number" min="0" step=".25" placeholder="Hours"><button class="primary" id="add">Add</button></div><textarea id="otj-description" placeholder="What did you do or learn?"></textarea></div>'+
 '<div class="card otj-download-card"><div><div class="section-title">Off-the-job evidence</div><h3>'+pending+' new '+(pending===1?"entry":"entries")+' ready for PDF</h3><p>Each saved entry includes the date and time. Downloading creates a PDF batch; anything added afterwards waits for the next PDF.</p></div><div class="row"><button class="primary" id="download-otj" '+(pending?"":"disabled")+'>Download new PDF</button>'+(lastBatch?'<button class="secondary" id="download-last-otj">Download last PDF again</button>':"")+'</div></div>'+
 '<div class="stats"><div class="card stat"><strong>'+total.toFixed(2)+'</strong><span>Total OTJ hours</span></div><div class="card stat"><strong>'+hours.length+'</strong><span>Learning entries</span></div></div>'+
 hours.slice().reverse().map(x=>'<div class="card otj-entry"><div class="progress-row"><strong>'+esc(Number(x.n).toFixed(2))+' hours</strong><span class="status '+(lastBatch&&Number(x.createdAt)<=Number(lastBatch.cutoff)?"done":"")+'">'+(lastBatch&&Number(x.createdAt)<=Number(lastBatch.cutoff)?"Downloaded":"New")+'</span></div><small class="otj-date">'+esc(x.savedAt||formatDateTime(x.createdAt))+'</small><p>'+esc(x.description||"No description recorded.")+'</p></div>').join("");
 $("#add").onclick=()=>{let n=Number($("#hrs").value),description=$("#otj-description").value.trim();if(n>0&&description){const now=Date.now();hours.push({id:"otj-"+now+"-"+Math.random().toString(36).slice(2,8),n:n,description:description,createdAt:now,savedAt:formatDateTime(now)});persist();learning()}else if(n>0){alert("Add a short description of what you did or learned before saving.")}};
 const dl=$("#download-otj");if(dl)dl.onclick=()=>downloadOTJPDF("new");
 const last=$("#download-last-otj");if(last)last.onclick=()=>downloadOTJPDF("last");
}
n)+' hours</strong><p>Off-the-job learning recorded on site</p><small style="color:#9aa7ba">'+esc(x.d)+'</small></div>').join("");
 $("#add").onclick=()=>{let n=Number($("#hrs").value);if(n>0){hours.push({n:n,d:new Date().toLocaleDateString("en-GB")});persist();learning()}};
}
function courses(){
 $("#page-title").textContent="Course";
 $("#screen").innerHTML=picker()+'<div class="card"><div class="section-title">'+esc(data().std)+'</div><h2>'+esc(data().name)+'</h2><p>'+data().u.length+' units. Open a unit to capture evidence.</p></div>'+data().u.map((u,i)=>'<div class="card unit-card" data-u="'+i+'"><div><div class="unit-number">UNIT '+(i+1)+'</div><div class="unit-title">'+esc(u[0])+'</div><div style="font-size:12px;color:#8e9aab;margin-top:6px">'+u[1].length+' linked KSBs</div></div><span class="arrow">›</span></div>').join("");
 bindCourses();document.querySelectorAll("[data-u]").forEach(b=>b.onclick=()=>openUnit(+b.dataset.u));
}
function bindCourses(){document.querySelectorAll("[data-c]").forEach(b=>b.onclick=()=>{course=b.dataset.c;persist();render()})}
function allK(){let m=new Map();data().u.forEach(u=>u[1].forEach(k=>m.set(code(k),text(k))));return [...m].sort((a,b)=>a[0][0].localeCompare(b[0][0])||Number(a[0].slice(1))-Number(b[0].slice(1)))}
function progress(){
 $("#page-title").textContent="Progress";let ev=new Set(evidence.filter(e=>e.c===course).flatMap(e=>e.k));
 $("#screen").innerHTML=picker()+'<div class="card"><div class="section-title">'+esc(data().std)+'</div><h2>KSB Progress</h2><p>Official KSB wording linked to this course. “Evidence captured” records saved evidence only; it is not an assessment decision.</p></div>'+allK().map(x=>'<div class="card progress-row"><div class="ksb"><span class="code">'+esc(x[0])+'</span><div class="ksbtext">'+esc(x[1])+'</div></div><span class="status '+(ev.has(x[0])?"done":"")+'">'+(ev.has(x[0])?"Captured":"Not captured")+'</span></div>').join("");
 bindCourses();
}
function portfolio(){
 $("#page-title").textContent="Portfolio";let es=evidence.filter(e=>e.c===course).slice().reverse();
 $("#screen").innerHTML=picker()+'<div class="card portfolio-intro"><div><div class="section-title">Completed evidence</div><h2>Portfolio</h2><p>Saved evidence for '+esc(data().name)+'.</p></div><button class="secondary pdf-button" id="download-pdf" '+(es.length?"":"disabled")+'>Download PDF</button></div>'+(es.length?es.map(e=>'<div class="card"><div class="progress-row"><div><div class="unit-number">'+esc(e.d)+'</div><h3>'+esc(e.u)+'</h3></div><span class="status done">Saved</span></div>'+(e.p.length?'<div class="photo-grid">'+e.p.map(p=>'<img class="thumb" src="'+p+'" alt="Evidence photo">').join("")+'</div>':"")+(e.w?'<p style="white-space:pre-wrap">'+esc(e.w)+'</p>':"")+
(e.signature?'<div class="evidence-signoff"><div class="unit-number">LEARNER SIGN-OFF</div><img src="'+e.signature+'" alt="Learner signature"><small>Signed by '+esc((e.learnerProfile&&e.learnerProfile.name)||"apprentice")+' · '+esc(e.savedAt||e.d)+'</small></div>':"")+
'<div class="row">'+e.k.map(k=>'<span class="pill">'+esc(k)+'</span>').join("")+'</div></div>').join(""):'<div class="empty-home" style="min-height:45vh"></div>');
 bindCourses();
 const download=$("#download-pdf");
 if(download)download.onclick=()=>window.downloadEvidencePack&&window.downloadEvidencePack();
}
function chat(){
 $("#modal-root").innerHTML='<div class="overlay"><section class="sheet"><div class="sheet-head"><h2>Evia</h2><button class="close" id="x">×</button></div><div class="chat" id="chat"><div class="bubble evia">Hi. I’m Evia. I can help you move around the app and your course.</div><div class="bubble evia">I’m a basic assistant for now — no AI assessment.</div></div><div class="chat-row"><input id="msg" placeholder="Talk to Evia…"><button class="primary" id="send">Send</button></div></section></div>';
 $("#x").onclick=()=>$("#modal-root").innerHTML="";
 const send=()=>{let v=$("#msg").value.trim();if(!v)return;let q=v.toLowerCase(),a=q.includes("course")?"Tap Course to see your units and capture evidence.":q.includes("progress")||q.includes("ksb")?"Progress lists the KSBs linked to your course.":q.includes("portfolio")||q.includes("evidence")?"Portfolio stores the evidence you have saved.":q.includes("learning")||q.includes("hour")?"Learning is where you record off-the-job hours.":"Use the five buttons at the bottom to move around Evia.";$("#chat").insertAdjacentHTML("beforeend",'<div class="bubble user">'+esc(v)+'</div><div class="bubble evia">'+a+'</div>');$("#msg").value="";$("#chat").scrollTop=$("#chat").scrollHeight};$("#send").onclick=send;$("#msg").onkeydown=e=>{if(e.key==="Enter")send()};
}
document.querySelectorAll("[data-nav]").forEach(b=>b.onclick=()=>nav(b.dataset.nav));
$("#evia-fab").onclick=chat;$("#profile-btn").onclick=()=>alert("Profile settings will be added here.");
render();
