[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-store, max-age=0"

[[headers]]
  for = "/sw-*.js"
  [headers.values]
    Cache-Control = "no-store, max-age=0"
