/* Evia test banks. Source copied from DDRNFinch/EPA main for offline learner testing. */
const EPA_DISCUSSIONS = {
  bricklaying: [
    {
      prompt: "You have been asked to build a section of brickwork from drawings. Talk through how you would prepare for the job and complete it to the required standard.",
      points: [
        { label: "Drawings", terms: ["drawing", "drawings", "plan", "section", "detail"] },
        { label: "Dimensions & setting out", terms: ["dimension", "dimensions", "setting out", "set out", "datum"] },
        { label: "Tools & PPE", terms: ["tools", "equipment", "ppe", "personal protective", "safety"] },
        { label: "Materials & mortar", terms: ["materials", "mortar", "mix", "cement", "sand"] },
        { label: "Line & level", terms: ["line", "level", "gauge", "bond", "finish", "quality"] }
      ]
    },
    {
      prompt: "You are starting a new wall and need to set it out accurately before laying the first course. Explain what you would do and how you would check your work.",
      points: [
        { label: "Drawings & dimensions", terms: ["drawings", "dimensions", "measurements", "specification"] },
        { label: "Starting datum", terms: ["datum", "starting point", "reference", "benchmark"] },
        { label: "Measure & mark", terms: ["measure", "mark", "tape", "setting out", "set out"] },
        { label: "Corners & bond", terms: ["corner", "corners", "opening", "bond", "return"] },
        { label: "Final measurements", terms: ["check", "recheck", "double check", "accuracy", "square"] }
      ]
    },
    {
      prompt: "You have mixed mortar and are about to begin laying bricks. Talk through how you would lay the bricks and keep the work accurate as the wall rises.",
      points: [
        { label: "Mortar consistency", terms: ["mortar", "consistency", "mix", "workable", "plastic"] },
        { label: "Bond & gauge", terms: ["bond", "gauge", "course", "brickwork"] },
        { label: "Line & level", terms: ["line", "level", "spirit level", "string line"] },
        { label: "Joint finish", terms: ["joints", "jointing", "finish", "perp", "bed joint"] },
        { label: "Quality checks", terms: ["check", "correct", "defect", "quality", "alignment"] }
      ]
    },
    {
      prompt: "You discover that part of your brickwork is not running true while you are building. Explain how you would identify the problem, correct it and prevent it happening again.",
      points: [
        { label: "Find the error", terms: ["stop", "identify", "check", "error", "problem"] },
        { label: "Line & level", terms: ["line", "level", "measure", "measurement", "gauge"] },
        { label: "Safe correction", terms: ["correct", "remove", "rebuild", "adjust", "refix"] },
        { label: "Bond & alignment", terms: ["bond", "joints", "alignment", "perp", "course"] },
        { label: "Drawings & specification", terms: ["drawings", "specification", "check", "dimensions", "tolerance"] }
      ]
    },
    {
      prompt: "At the end of the job you need to leave the work area safe and the finished brickwork ready for inspection. Talk through what you would do.",
      points: [
        { label: "Final inspection", terms: ["inspect", "inspection", "check", "quality", "finished"] },
        { label: "Line & joints", terms: ["line", "level", "gauge", "bond", "joints"] },
        { label: "Defects", terms: ["defect", "defects", "repair", "correct", "unfinished"] },
        { label: "Tools & materials", terms: ["clean", "tools", "materials", "store", "storage"] },
        { label: "Housekeeping", terms: ["clean", "safe", "housekeeping", "waste", "hazard"] }
      ]
    }
  ],
  siteCarpentry: [
    {
      prompt: "You have been asked to construct and install a timber door frame from drawings. Talk through how you would prepare, make and install it.",
      points: [
        { label: "Drawings & specification", terms: ["drawings", "drawing", "specification", "plan", "detail"] },
        { label: "Dimensions & setting out", terms: ["dimensions", "measure", "setting out", "set out", "measurements"] },
        { label: "Tools & PPE", terms: ["tools", "equipment", "ppe", "safety", "personal protective"] },
        { label: "Cut & assemble", terms: ["cut", "cutting", "assemble", "joint", "jointing"] },
        { label: "Install & check", terms: ["install", "fix", "plumb", "level", "check"] }
      ]
    },
    {
      prompt: "You are preparing to build a section of a timber floor. Explain how you would interpret the information, prepare the materials and construct it correctly.",
      points: [
        { label: "Drawings & details", terms: ["drawings", "details", "plan", "specification", "interpret"] },
        { label: "Joist setting out", terms: ["set out", "setting out", "joists", "dimensions", "centres"] },
        { label: "Timber & fixings", terms: ["timber", "fixings", "tools", "materials", "nails"] },
        { label: "Joist support", terms: ["joists", "spacing", "support", "bearing", "centres"] },
        { label: "Level & alignment", terms: ["level", "alignment", "straight", "check", "structural"] }
      ]
    },
    {
      prompt: "A roof opening is required for a loft hatch. Talk through how you would prepare and form the opening safely and accurately.",
      points: [
        { label: "Drawings & opening", terms: ["drawings", "opening", "size", "dimensions", "plan"] },
        { label: "Existing structure", terms: ["structure", "check", "inspect", "joists", "existing"] },
        { label: "Opening setting out", terms: ["set out", "setting out", "measure", "mark", "dimensions"] },
        { label: "Cutting & support", terms: ["cut", "cutting", "support", "temporary", "safety"] },
        { label: "Trimmers & checks", terms: ["trimmer", "trimmers", "fix", "level", "check"] }
      ]
    },
    {
      prompt: "You are fitting skirting and architrave in a room with several corners and openings. Explain how you would achieve a neat professional finish.",
      points: [
        { label: "Measure & sequence", terms: ["measure", "measurements", "plan", "sequence", "layout"] },
        { label: "Timber & tools", terms: ["timber", "tools", "material", "materials", "saw"] },
        { label: "Corner joints", terms: ["joints", "mitre", "scribe", "cut", "corners"] },
        { label: "Secure fixing", terms: ["fix", "fixings", "nails", "adhesive", "secure"] },
        { label: "Alignment & finish", terms: ["alignment", "level", "straight", "finish", "quality"] }
      ]
    },
    {
      prompt: "You have completed a site carpentry task and are preparing the work for inspection. Talk through your final checks and how you would deal with any defects.",
      points: [
        { label: "Drawings & inspection", terms: ["inspect", "inspection", "drawings", "specification", "check"] },
        { label: "Measurements & alignment", terms: ["measurements", "dimensions", "level", "alignment", "plumb"] },
        { label: "Joints & fixings", terms: ["joints", "fixings", "secure", "joint", "fixed"] },
        { label: "Defects & correction", terms: ["defects", "defect", "correct", "repair", "rectify"] },
        { label: "Housekeeping", terms: ["tools", "clean", "tidy", "safe", "housekeeping"] }
      ]
    }
  ],
  benchJoinery: [
    {
      prompt: "You have been asked to make a timber window frame from a drawing in the workshop. Talk through how you would prepare, machine, assemble and finish the job.",
      points: [
        { label: "Drawing & specification", terms: ["drawing", "drawings", "specification", "details", "plan"] },
        { label: "Timber selection", terms: ["timber", "wood", "material", "prepare", "moisture"] },
        { label: "Tools & machinery", terms: ["tools", "machine", "machines", "ppe", "safety"] },
        { label: "Joints & assembly", terms: ["joints", "joint", "mortice", "tenon", "assemble"] },
        { label: "Dimensions & finish", terms: ["dimensions", "square", "squareness", "finish", "quality"] }
      ]
    },
    {
      prompt: "You need to produce a mortice and tenon joint for a joinery component. Explain how you would mark out, machine or cut, assemble and check the joint.",
      points: [
        { label: "Joint dimensions", terms: ["drawing", "dimensions", "joint", "specification", "size"] },
        { label: "Marking out", terms: ["mark out", "marking out", "gauge", "square", "measure"] },
        { label: "Safe tool use", terms: ["machine", "machinery", "tools", "ppe", "safety"] },
        { label: "Mortice & tenon", terms: ["mortice", "tenon", "accurate", "clean", "fit"] },
        { label: "Dry assembly", terms: ["dry assemble", "assemble", "fit", "check", "glue"] }
      ]
    },
    {
      prompt: "A component you have made does not fit its mating component correctly. Talk through how you would find the cause and put it right.",
      points: [
        { label: "Inspect components", terms: ["stop", "inspect", "check", "components", "parts"] },
        { label: "Drawings & dimensions", terms: ["drawings", "dimensions", "measurements", "specification", "size"] },
        { label: "Marking & machining", terms: ["marking out", "machining", "joint", "accuracy", "machine"] },
        { label: "Controlled adjustment", terms: ["adjust", "adjustment", "correct", "remove", "trim"] },
        { label: "Test fit", terms: ["fit", "test", "check", "quality", "finish"] }
      ]
    },
    {
      prompt: "You are preparing a finished joinery component for sanding and final finishing. Explain how you would inspect and prepare it.",
      points: [
        { label: "Inspect defects", terms: ["inspect", "defects", "defect", "check", "damage"] },
        { label: "Dimensions & accuracy", terms: ["dimensions", "joints", "accuracy", "square", "measure"] },
        { label: "Surface preparation", terms: ["sanding", "sand", "surface", "marks", "abrasive"] },
        { label: "Edges & profile", terms: ["edges", "profile", "protect", "detail", "finish"] },
        { label: "Ready for finishing", terms: ["clean", "finish", "finishing", "dust", "ready"] }
      ]
    },
    {
      prompt: "You are completing a bench joinery job and need to present it for inspection. Talk through your final quality checks, documentation and workshop housekeeping.",
      points: [
        { label: "Compare drawing", terms: ["drawing", "drawings", "specification", "compare", "check"] },
        { label: "Dimensions & fit", terms: ["dimensions", "square", "joints", "fit", "measurements"] },
        { label: "Surface finish", terms: ["finish", "surface", "defects", "quality", "appearance"] },
        { label: "Report issues", terms: ["record", "report", "issues", "defects", "documentation"] },
        { label: "Workshop housekeeping", terms: ["clean", "bench", "tools", "safe", "housekeeping"] }
      ]
    }
  ]
};


const EPA_MATHS_QUESTIONS=[
["Fractions, Decimals and Percentages","A trade merchant prices a pack of timber at £150 before applying a 20% trade discount.",["£110.00","£120.00","£130.00","£140.00"],"£120.00","To find a 20% discount, calculate 20% of £150 (£30) and subtract it from the original total (£150 - £30 = £120).","If an item costs £40 and has a 25% discount (£10 off), what is the final price?",["£30","£35"],"£30"],
["Fractions, Decimals and Percentages","An apprentice completes 18 out of a total target of 24 flooring boards. What percentage of the target has been completed?",["65%","70%","75%","80%"],"75%","Divide the part by the total (18 ÷ 24 = 0.75) and multiply by 100 to get 75%.","If you score 3 out of 4 on a test, what is that as a percentage?",["75%","60%"],"75%"],
["Fractions, Decimals and Percentages","A material budget increases from £500 to £550 over the year. What is the percentage increase in the budget?",["5%","10%","15%","20%"],"10%","Find the increase (£50), divide it by the original amount (£500), and multiply by 100 (50 ÷ 500 = 0.10, or 10%).","If a price goes up by £10 from an original £100, what is the percentage increase?",["10%","5%"],"10%"],
["Ratio, Proportion and Scaling","A mortar mix uses cement and sand in the ratio 1 : 3. If you use 3 bags of cement, how many bags of sand do you need?",["6 bags","8 bags","9 bags","12 bags"],"9 bags","For every 1 part of cement, you need 3 parts of sand. Multiply the cement amount by 3 (3 × 3 = 9).","If the ratio is 1 : 2 and you use 4 bags of cement, how much sand do you need?",["8 bags","6 bags"],"8 bags"],
["Ratio, Proportion and Scaling","If 2 workers can complete a site hoarding installation in 6 days, how many days will it take 4 workers to complete the exact same task working at the same rate?",["2 days","3 days","4 days","12 days"],"3 days","This is inverse proportion. Multiply workers by days to find total worker-days (2 × 6 = 12), then divide by the new worker count (12 ÷ 4 = 3 days).","If 2 workers take 4 days to paint a wall, how many days for 4 workers?",["2 days","4 days"],"2 days"],
["Ratio, Proportion and Scaling","On an architectural scale drawing, a dimension of 20 mm represents an actual length of 1 metre (1,000 mm). What is the scale ratio?",["1 : 20","1 : 50","1 : 100","1 : 200"],"1 : 50","Divide the actual measurement (1,000 mm) by the drawing measurement (20 mm) to find the scale factor (1,000 ÷ 20 = 50), giving a ratio of 1 : 50.","If 10 mm represents 100 mm, what is the scale ratio?",["1 : 10","1 : 20"],"1 : 10"],
["Measures, Shape and Space","What is the area of a rectangular workshop floor measuring 6 metres long by 4 metres wide?",["10 m²","20 m²","24 m²","36 m²"],"24 m²","Area is calculated by multiplying length by width (6 × 4 = 24), not by adding them together.","What is the area of a rug measuring 3 m by 3 m?",["9 m²","6 m²"],"9 m²"],
["Measures, Shape and Space","A room measures 5 m long and 3 m wide. What is the total perimeter of the room?",["8 m","15 m","16 m","25 m"],"16 m","Perimeter is the total distance around the outside. Add all four sides together (5 + 5 + 3 + 3 = 16 m).","What is the perimeter of a square with sides measuring 2 m?",["8 m","6 m"],"8 m"],
["Measures, Shape and Space","What is the volume of a rectangular storage box measuring 2 m long, 1 m wide, and 1.5 m high?",["3.0 m³","4.5 m³","6.0 m³","7.5 m³"],"3.0 m³","Volume is length × width × height (2 × 1 × 1.5 = 3.0 m³).","What is the volume of a box measuring 2 m × 2 m × 2 m?",["8 m³","6 m³"],"8 m³"],
["Handling Data and Statistics","An apprentice records the following daily timber cutting times in minutes: 30, 40, 50, 40, 60. What is the median time?",["35 minutes","40 minutes","45 minutes","50 minutes"],"40 minutes","Put the numbers in order from smallest to largest (30, 40, 40, 50, 60). The middle value is 40.","Find the median of these numbers: 10, 20, 30.",["20","10"],"20"],
["Handling Data and Statistics","A builder records daily delivery delays in minutes over 4 days: 10, 20, 0, 10. What is the mean (average) delay?",["5 minutes","10 minutes","15 minutes","20 minutes"],"10 minutes","Add all values together (10 + 20 + 0 + 10 = 40) and divide by the number of days (4), giving 40 ÷ 4 = 10.","Find the mean of 2, 4, and 6.",["4","6"],"4"],
["Handling Data and Statistics","A set of test scores ranges from a minimum of 45 to a maximum of 85. What is the range of the dataset?",["30","40","45","130"],"40","The range is the highest value minus the lowest value (85 - 45 = 40).","What is the range if the highest score is 50 and the lowest score is 20?",["30","20"],"30"]
];

const EPA_ENGLISH_QUESTIONS=[
["Reading Comprehension, Inference and Analysis","Read this project review excerpt: “Whilst the site supervisor completed the framing phase early, one wonders if electrical snags could have been avoided with better communication.” What is the writer’s attitude?",["Unconditional praise for all management","Balanced, acknowledging speed while questioning communication","Complete dismissal of the construction project","Supportive of electrical teams only"],"Balanced, acknowledging speed while questioning communication","The writer notes a positive (“completed... early”) but also raises a critique (“wondered if... avoided”), showing a balanced viewpoint.","Identify the tone: “The work is neat, but it took twice as long.”",["Balanced / Critical","Unconditionally positive"],"Balanced / Critical"],
["Reading Comprehension, Inference and Analysis","Read this tool advertisement: “Our new drill is simply the most revolutionary, indestructible engineering marvel ever made.” What stylistic feature is used here?",["Objective technical data reporting","Subjective hyperbole and persuasive marketing language","Formal health and safety regulation text","Neutral instructional manual text"],"Subjective hyperbole and persuasive marketing language","Words like “indestructible marvel” are exaggerated claims meant to persuade buyers, which is known as hyperbole.","Is “This hammer is okay” or “This is the greatest hammer in the universe!” an example of advertising hyperbole?",["This is the greatest hammer in the universe!","This hammer is okay"],"This is the greatest hammer in the universe!"],
["Reading Comprehension, Inference and Analysis","When comparing two articles on housing development written by a property developer and a local resident, what core skill is required?",["Memorizing every single word","Identifying differing bias, viewpoints, and motivations","Assuming both authors feel the exact same way","Ignoring the authors’ backgrounds"],"Identifying differing bias, viewpoints, and motivations","Different writers have different personal stakes, so you must look at how their background creates bias or shapes their viewpoint.","Would a business owner and a customer have different views on high prices?",["Yes, their differing perspectives shape their viewpoint.","No, they would always have the same viewpoint."],"Yes, their differing perspectives shape their viewpoint."],
["Writing Composition, Structure and Formal Register","When drafting a formal technical report for college management, which register is appropriate?",["Informal slang and casual abbreviations","Objective, professional tone structured with clear headings","Highly emotional and dramatic storytelling","Text-message shorthand"],"Objective, professional tone structured with clear headings","Formal reports require a professional, objective tone and clear layout, avoiding slang or emotional language.","Choose the more formal sentence: “The tool broke down” or “The equipment experienced a mechanical failure.”",["The equipment experienced a mechanical failure.","The tool broke down"],"The equipment experienced a mechanical failure."],
["Writing Composition, Structure and Formal Register","Which transitional word is best for introducing a contrasting argument in a paragraph?",["Consequently","Furthermore","However","Similarly"],"However","“However” is used specifically to signal a contrast or shift away from a previous point.","To show a contrast between liking tea and disliking coffee, which word fits best: Furthermore or However?",["However","Furthermore"],"However"],
["Writing Composition, Structure and Formal Register","Which sentence uses proper formal vocabulary for an incident report?",["The worker slipped on grease and went flying.","An operative experienced a slip hazard due to uncontained lubricant spillage.","It was really bad when someone fell down today.","Guys on site need to watch out."],"An operative experienced a slip hazard due to uncontained lubricant spillage.","Formal reports require professional terminology like “operative” and “spillage” instead of casual slang like “went flying” or “guys”.","Choose the formal term for “messy”: Untidy hazard or Gross state.",["Untidy hazard","Gross state"],"Untidy hazard"],
["Spelling, Punctuation and Grammar","Choose the sentence that punctuates an embedded relative clause correctly with commas.",["The safety officer who inspected the scaffolding yesterday issued a notice.","The safety officer, who inspected the scaffolding yesterday, issued a notice.","The safety officer who inspected the scaffolding, yesterday issued a notice.","The safety officer, who inspected the scaffolding yesterday issued a notice."],"The safety officer, who inspected the scaffolding yesterday, issued a notice.","Extra descriptive clauses embedded in the middle of a sentence must be wrapped in a pair of commas.","Fix this clause with commas: “My car which is red is fast.”",["My car, which is red, is fast.","My car which is red is fast."],"My car, which is red, is fast."],
["Spelling, Punctuation and Grammar","Which of the following words is spelled correctly?",["Enviroment","Environment","Enviornment","Envrionment"],"Environment","Remember that environment contains a middle “n” right before the “m”.","Choose the correct spelling: necessary or necissary.",["necessary","necissary"],"necessary"],
["Spelling, Punctuation and Grammar","Identify the sentence that keeps consistent verb tense throughout.",["The apprentice measures the timber and then cuts the joint.","The apprentice measured the timber and cuts the joint.","The apprentice measures the timber and cut the joint.","The apprentice measuring the timber and cut the joint."],"The apprentice measures the timber and then cuts the joint.","Both verbs need to match in tense. Option A uses the present tense for both (“measures” and “cuts”).","Fix the tense mismatch: “He walks to work and ran home.”",["He walks to work and runs home.","He walks to work and ran home."],"He walks to work and runs home."]
];

const EPA_QUESTIONS = {
bricklaying: [
["K1","What is the primary legislation that imposes a general duty on employers to ensure, so far as is reasonably practicable, the health, safety, and welfare at work of all employees?",["The Health and Safety at Work etc. Act 1974","The Construction Design and Management Regulations","The Control of Substances Hazardous to Health Act","The Provision and Use of Work Equipment Regulations"]],
["K2","Which of the following is the correct protocol regarding the inspection and use of Personal Protective Equipment (PPE) on site?",["Inspect PPE before every single use and report any defects immediately","Inspect PPE only when it begins to show visible signs of structural failure","Inspect PPE on a monthly basis during formal company safety audits","Inspect PPE annually alongside statutory portable appliance testing"]],
["K3","What document is typically issued immediately prior to high-risk site operations to detail the exact step-by-step procedure to be followed to control identified hazards?",["A comprehensive risk assessment and method statement document","A generic company health and safety policy handbook statement","A statutory project environmental impact assessment schedule","A routine pre-start site induction and tool box talk briefing"]],
["K4","Which construction site practice directly contributes to minimizing environmental impact through the efficient management of surplus materials?",["Segregating waste streams on site to maximize local recycling potential","Disposing of all non-hazardous packaging materials into general skips","Burning untreated timber offcuts safely within designated open areas","Transporting excess mortar slurry directly to local municipal landfills"]],
["K5","What physical building characteristic is primarily designed to prevent unwanted air leakage through the building envelope, thereby improving thermal efficiency?",["Continuous airtightness detailing across external wall interfaces","Increased cavity width dimensions filled with mineral wool batts","High compressive strength concrete foundation block placement","External decorative brick joint finishes tooled to a weather strike"]],
["K6","Which critical structural component spans across door and window openings within a masonry wall to safely transfer superimposed loads to the jambs?",["A pre-stressed concrete or galvanized steel structural lintel","A continuous damp proof course membrane layer of polythene","A flexible wall tie spacing configuration fixed at vertical centres","An internal timber frame sole plate secured down to masonry"]],
["K7","Which official regulatory document sets out mandatory performance standards for the design and construction of buildings in England to ensure structural integrity?",["The government approved national building regulations documents","The voluntary British Standards Institution design specifications","The independent structural warranty provider technical manuals","The local municipal authority urban planning policy guidance"]],
["K8","What surface crystalline defect often appears on newly constructed brickwork as a white powdery deposit caused by soluble salts drawing out of the mortar?",["Efflorescence caused by moisture dissolving and migrating internal salts","Carbonation caused by atmospheric reaction with exposed free lime","Spalling caused by repeated freeze-thaw cycles on saturated clay","Hydration failure caused by premature drying out of cement binders"]],
["K9","Which modern method of construction involves manufacturing structural building elements off-site in a controlled factory environment prior to rapid assembly?",["Precast concrete component installation and modular pod systems","Traditional hand mixing of proprietary lime mortar on open ground","Standard stretcher bond brickwork built using adjustable profiles","Site-batched aggregate placement utilizing mechanical site mixers"]],
["K10","Which architectural drawing type provides a vertical cut-through view of a building to show internal floor levels, foundation details, and roof construction?",["A detailed architectural cross-section drawing of the structure","A comprehensive site location block plan layout drawing view","An exterior front elevation projection drawing of the facade","A dimensional floor layout setting out plan arrangement drawing"]],
["K11","What collaborative digital design process utilizes intelligent 3D models to give construction professionals insight into planning, designing, and constructing?",["Building Information Modelling software visualization systems","Computer Aided Manufacturing automated production scripts","Digital Photogrammetry surveying data processing packages","Electronic Spreadsheet resource estimation calculation tools"]],
["K12","When estimating material quantities for a standard brick wall, what standard allowance is typically added to the calculated total brick count for site wastage?",["An additional five to ten percent allowance for site cutting and breakages","An additional twenty to twenty-five percent contingency buffer volume","A fixed minimum allowance of exactly two hundred extra units per pack","No additional allowance since theoretical calculations include waste"]],
["K13","Which specialist bricklaying hand tool is specifically designed and shaped to achieve a concave, compacted finish on freshly laid mortar joints?",["A tubular steel or curved brass barrel brick jointer tool","A heavy forged carbon steel pointing trowel blade edge","A rectangular plastic finishing float used for rendering","A double-ended mason club hammer used for cutting bricks"]],
["K14","What primary safety hazard is associated with the continuous dry cutting of concrete blocks using a high-speed abrasive disc cutter without suppression?",["Inhalation of hazardous respirable crystalline silica dust particles","Instantaneous thermal combustion of nearby petroleum solvents","Excessive acoustic vibration transfer causing acute hand-arm injury","Complete electrical motor burnout due to heavy mechanical load"]],
["K15","Which traditional brick bond pattern consists entirely of alternating courses of full headers and full stretchers showing on the visible wall face?",["A traditional English bond pattern featuring alternating course types","A standard Flemish bond pattern featuring alternating units per course","A garden wall running bond pattern featuring repeating stretcher runs","A modern stack bond pattern featuring vertically aligned perpends"]],
["K16","What is the primary purpose of finishing the top of a freestanding brick boundary solid wall with a sloping protective coping detail?",["To shed rainwater away from the corework and prevent frost damage","To increase the overall compressive load bearing capacity limit","To provide a secure fixing base for decorative wrought iron railings","To conceal any minor dimensional leveling errors in the top course"]],
["K17","Which mortar joint profile is formed with a recessed angle that actively throws rainwater away from the face of the brickwork to prevent ingress?",["A traditional weathered or weather-struck mortar joint finish","A smooth half-round bucket handle concave mortar joint profile","A flush troweled mortar joint finished flat with the brick face","A deep square-raked mortar joint profile set back from the edge"]],
["K18","In brickwork construction, what term describes a structural pillar that is built projecting outward from and bonded directly into a main wall?",["An attached or engaged structural brick masonry pier support","An isolated freestanding structural brick column construction","A decorative horizontal contrasting brick banding course detail","A vertical expansion movement joint formed with soft foam filler"]],
["K19","Why are vertical movement or expansion joints incorporated into long elevations of brickwork built with modern clay facing materials?",["To accommodate thermal expansion and moisture-related structural movement","To act as a primary damp proof barrier against lateral water tracking","To provide a clean vertical stopping point for daily shift progress","To divide the structural load equally across different foundation pads"]],
["K20","When hand-mixing mortar on site using building sand and ordinary Portland cement, what is the standard volumetric ratio commonly used for general bricklaying?",["One part cement to six parts building sand with plasticiser additive","One part cement to one part lime to three parts sand aggregate","Two parts cement to four parts coarse sharp aggregate and water","One part cement to ten parts soft building sand without additives"]],
["K21","What leveling tool is traditionally positioned at the corners of a cavity wall build to establish accurate course heights and maintain plumb alignment?",["Timber or aluminum corner profile gauges marked with course lines","Rotary laser leveling instruments mounted on heavy tripod bases","Digital electronic spirit levels fitted with dual audio alarms","Traditional brass plumb bobs suspended on fine nylon strings"]],
["K22","What is the primary function of plastic or stainless steel wall ties installed across a masonry cavity wall construction during building operations?",["To tie the inner and outer masonry leaves together to resist wind loads","To bridge the thermal insulation gap and provide structural rigidity","To support the weight of internal timber floor joist hanger brackets","To act as a secondary barrier preventing vertical moisture movement"]],
["K23","How is a brick soldier course typically positioned when incorporated as a decorative or structural feature above an external window opening?",["Laid vertically on end with their long narrow faces exposed outward","Laid flat on their broad bed faces with stretchers facing forward","Laid on their long edge faces with headers facing outward to view","Laid at a forty-five degree diagonal angle within a stepped reveal"]],
["K24","When replacing a damaged brick within an existing wall panel, what is the first physical task required after raking out the surrounding mortar joints?",["Carefully drilling or breaking out the damaged unit without disturbing neighbors","Wetting the exposed cavity thoroughly with a high-pressure water hose","Applying a heavy layer of fresh rapid-setting epoxy adhesive mortar","Inserting temporary timber props to support the courses directly above"]],
["K25","What protective measure must be applied to newly laid brickwork when ambient temperatures are forecast to drop below freezing point overnight?",["Covering the exposed masonry securely with insulating frost blankets","Spraying the fresh mortar joints with a diluted chemical accelerator","Heating the wall surface continuously with high-output gas heaters","Drenching the brickwork in cold water to seal the surface pores"]],
["K26","Why is it critical for construction operatives to use accurate industry terminology when verbally reporting progress or defects on site?",["To ensure clear, unambiguous communication and prevent costly errors","To satisfy statutory occupational health and safety audit requirements","To comply with international linguistic translation software standards","To maintain strict professional hierarchy boundaries among staff"]],
["K27","What is a key attribute of effective team working when multiple bricklaying squads are working concurrently on a fast-track residential development?",["Proactively sharing resources, materials, and information to maintain flow","Working strictly in isolation to avoid any overlap of daily site duties","Competing against other squads to achieve the highest daily output rate","Delegating all physical material transport tasks to junior apprentices"]],
["K28","How does promoting equity, diversity, and inclusion positively impact team performance within a modern construction site environment?",["By fostering a respectful culture that encourages collaboration and wellbeing","By ensuring all workers receive identical rates of pay regardless of skill","By eliminating the need for formal site inductions and toolbox briefings","By standardizing individual working methods across every trade group"]],
["K29","When using a bolster chisel and club hammer to cut a standard clay brick by hand, what is the correct technique to ensure a clean break?",["Score all four sides lightly with the bolster before striking a firm blow","Place the brick on a soft sand bed and strike the center repeatedly","Hit the bolster chisel at an acute angle toward the waste portion","Submerge the brick in water for one hour prior to striking the chisel"]],
["K30","When setting out a brick wall with a raking cut for a gable end, what mathematical tool or calculation is used to establish the correct gradient angle?",["The roof pitch angle from architectural drawings transferred via gauge rod","A standard ninety-degree builder square placed against the foundation","A 3-4-5 geometric triangle ratio measured with a flexible tape measure","An optical transit level rotated to an arbitrary forty-five degree mark"]],
["K31","What immediate action should an operative take if they notice a colleague showing signs of severe stress or mental health difficulties on site?",["Approach them privately, listen without judgment, and signpost support","Report them immediately to senior management for disciplinary review","Advise them to take extended annual leave without discussing work","Ignore the behavior to avoid invading their personal privacy rights"]],
["S1","Prior to commencing excavation or masonry work near an overhead power line, what primary safety check must an operative perform?",["Verify safe working clearance distances and check for permit requirements","Measure the wind speed using an anemometer mounted on a pole","Ensure all nearby workers are wearing high-visibility waterproof jackets","Test the electrical conductivity of the adjacent soil using a meter"]],
["S2","When selecting respiratory protective equipment (RPE) for protection against fine silica dust, what factor must be verified?",["That the filter rating matches the hazard and a face-fit test is valid","That the mask is brightly colored to ensure high site visibility","That the facepiece is manufactured entirely from flexible silicone rubber","That the unit features an integrated battery-powered cooling fan"]],
["S3","What is the correct procedure for handling clean waste brick offcuts on a sustainable construction site project?",["Segregate them into a designated hard inert material skip for crushing","Mix them into general municipal waste containers for off-site disposal","Scatter them across excavated earth areas to act as sub-base fill","Stack them neatly outside the site boundary for local public collection"]],
["S4","When building external masonry within specified tolerances, which reference document dictates the maximum allowable plumb deviation per story height?",["British Standards and approved trade association technical guidance codes","The local municipal authority residential council tax banding policy","The commercial property developer internal marketing brochure manual","The civil engineering contractor corporate social responsibility brief"]],
["S5","An architectural drawing shows a window opening dimension labeled with a metric measurement. What unit of measurement is standard on UK construction drawings?",["Millimeters used consistently for all dimensional drawing annotations","Centimeters used for all vertical height and horizontal span details","Meters used exclusively for all internal room layout dimensioning","Inches and feet used in accordance with traditional imperial standards"]],
["S6","When calculating the amount of wall ties required for a new cavity wall installation, what standard density per square meter is typically specified?",["Two and a half ties per square meter evenly distributed across the area","Exactly one tie per every single individual brick laid in the outer leaf","Five structural ties per square meter concentrated around all openings","Ten heavy-duty stainless steel ties per square meter near ground level"]],
["S7","What is the most effective method for maintaining a safe working platform on a scaffold staging during active bricklaying operations?",["Keep board surfaces clear of excess mortar, rubbish, and tripping hazards","Wash down all working boards with high-pressure water twice daily","Cover all scaffold boards with thick plastic sheeting to protect timber","Stack surplus packs of bricks directly on the outer edge of boards"]],
["S8","When selecting a trowel for buttering mortar onto standard facing bricks, what size of brick trowel is typically preferred by experienced tradespeople?",["A ten to eleven-inch London pattern brick trowel for balanced loading","A four-inch miniature pointing trowel for general block laying tasks","A fifteen-inch heavy plastering trowel for maximum mortar carriage","A rigid triangular gauging trowel for mixing small adhesive batches"]],
["S9","What routine maintenance task should be performed on steel bricklaying trowels at the end of every working shift?",["Clean off all residual mortar, wipe dry, and lightly oil the steel blade","Submerge the entire metal blade and handle in concentrated acid solution","Sharpen the tip of the blade on a high-speed bench grinder wheel","Store the tools uncleaned inside a damp wooden toolbox compartment"]],
["S10","When setting out the damp proof course (DPC) at foundation level for a cavity wall, what critical geometric check must be carried out?",["Measure diagonal corner-to-corner dimensions to confirm squareness","Check that the total wall length matches the boundary fence exactly","Verify that the sub-floor hardcore is compacted to maximum density","Ensure the outer leaf overhangs the concrete foundation by fifty millimeters"]],
["S11","During the construction of a brick and block cavity wall opening, what must be installed immediately above the insulated cavity tray?",["Open vertical perpends acting as weep holes for drainage","A continuous strip of timber grounds for internal fixings","A heavy layer of expanding polyurethane foam insulation sealant","An extra course of engineering bricks laid flat on bed"]],
["S12","When is the optimum time to tool freshly laid mortar joints to achieve a uniform, high-quality weather-struck or bucket-handle finish?",["When the mortar has stiffened to thumbprint hardness across the face","Immediately while the mortar is still completely wet and fluid","Twenty-four hours after the entire wall section has fully cured","Just before applying the final cleaning acid wash to the brickwork"]],
["S13","When constructing a simple brick solid garden wall, what is the purpose of incorporating piers at regular intervals along long straight runs?",["To provide lateral stability against wind overturning forces","To act as designated movement joints for thermal expansion","To support internal timber floor joist loads spanning across","To enhance the decorative appearance of the boundary line"]],
["S14","What measuring method ensures consistent batch proportions when hand-mixing mortar using cement, sand, and plasticiser on site?",["Utilizing dedicated clean gauge buckets or volume-calibrated banker boxes","Estimating quantities visually by eye within a standard mixing wheelbarrow","Weighing every individual bag of cement on electronic platform scales","Measuring water flow duration using a stopwatch during hose filling"]],
["S15","When cutting facing bricks with a bolster and hammer to fit a specific closing dimension, what personal protective equipment is essential?",["Impact-resistant safety glasses and robust protective safety gloves","A high-visibility waterproof jacket and heavy-duty rubber boots","A powered air-fed respiratory helmet and ear defender muffs","A flame-retardant welder apron and thermal gauntlet gloves"]],
["S16","When cutting out a cracked and damaged facing brick for replacement, what tool is used to remove the old mortar beds without damaging neighbors?",["A carbide-tipped mortar raking chisel or oscillating multi-tool","A heavy pneumatic demolition breaker fitted with a wide spade bit","A standard nine-inch abrasive cutting disc mounted on a grinder","A blunt brick hammer struck repeatedly at a perpendicular angle"]],
["S17","How should stacks of high-quality facing bricks be stored on site prior to laying to protect them from ground moisture and efflorescence?",["Raised off the ground on timber battens and covered with waterproof sheeting","Stacked directly onto muddy ground in neat unsealed open packs","Immersed fully in water tanks to ensure complete saturation before use","Stored inside a heated site office container away from natural air"]],
["S18","When communicating brickwork setting-out requirements to a crane operator lifting material pallets, what communication method should be used?",["Standardized hand signaling codes or a dedicated two-way radio","Loud verbal shouting across the site accompanied by wild waving","Written notes passed through intermediate laborers on the ground","Laser pointer beams directed at the landing platform surface"]],
["S19","If an apprentice witnesses exclusionary behavior or derogatory remarks on a bricklaying project, what is the appropriate course of action?",["Challenge the behavior safely or report it through company procedures","Ignore the incident completely to avoid personal conflict on site","Retaliate immediately with matching verbal remarks on the offender","Leave the construction site immediately without informing anyone"]],
["S20","How can a bricklayer best support the wider build team, including scaffolders and groundworkers, during a busy foundation stage?",["Coordinate deliveries and clear access routes to prevent bottlenecks","Focus exclusively on laying brickwork without regard for other trades","Complete all tasks independently without asking for or offering help","Take frequent extended breaks to allow other trades undisputed access"]],
["S21","Where can a construction worker find confidential helplines and practical advice regarding mental health support within the UK construction industry?",["Dedicated industry charities such as the Lighthouse Construction Industry Charity","Local municipal authority council tax collection office reception desks","Commercial building material manufacturer product warranty brochures","National highway maintenance emergency breakdown service centers"]],
["S22","When laying a brick course that requires a raking cut along a gable slope, how is the exact cutting angle transferred onto the brick face?",["Using a sliding bevel gauge set against a pitched profile board","Estimating the angle visually by eye against a spirit level bubble","Measuring the diagonal span with a standard steel measuring tape","Using a ninety-degree builder square placed flat on the mortar bed"]],
["B1","Which behavioral trait best demonstrates an individual putting health, safety, and wellbeing first on a busy bricklaying site?",["Stopping work immediately to challenge an unsafe working practice observed nearby","Wearing required PPE only when site safety inspectors are visibly present","Working through rest breaks to ensure daily production targets are fully met","Ignoring minor near-miss incidents to prevent slowing down progress schedules"]],
["B2","How does a worker with a strong environmental consciousness typically handle surplus mortar at the end of a working day?",["Recycles or disposes of it responsibly according to site environmental plans","Tips leftover wet mortar down nearby drainage inspection chambers","Scatters hardened mortar waste across open landscaped soil areas","Burns dried mortar packaging bags in an unapproved open fire pit"]],
["B3","What behavior reflects taking full personal ownership and accountability for the quality of one's bricklaying output?",["Inspecting own work regularly with a spirit level and rectifying errors promptly","Relying entirely on site supervisors to spot and correct alignment mistakes","Blaming poor material quality for any out-of-plumb brickwork completed","Leaving snagging items for the finishing trades to resolve during handover"]],
["B4","Which action demonstrates a proactive contribution to an inclusive and diverse working culture on a construction project?",["Actively welcoming colleagues from all backgrounds and respecting their views","Forming exclusive working groups based on personal social preferences","Avoiding conversation with newly arrived trade contractors on site","Making casual jokes about cultural differences to break initial tension"]],
["B5","What behavior indicates an active commitment to seeking learning and development opportunities within the bricklaying trade?",["Asking experienced craftspeople for tips on complex detailing and advanced methods","Believing that initial college training provides all necessary lifelong skills","Avoiding unfamiliar tasks to prevent making errors in front of peers","Refusing to attend manufacturer product demonstrations during work hours"]],
["B6","How does a team-focused bricklayer behave when their own section of walling is completed ahead of schedule?",["Offers assistance to colleagues or helps prepare materials for the next stage","Ceases work early and waits in the site canteen until clock-out time","Criticizes slower-working team members for delaying overall progress","Commences unauthorized work on unrelated trades without coordination"]]
],
siteCarpentry: [],
benchJoinery: []
};

const JOINERY = [
["K1","Which specific UK statutory regulation places duties on employers and employees regarding the safe provision and use of work equipment such as circular saws?",["The Provision and Use of Work Equipment Regulations (PUWER)","The Control of Substances Hazardous to Health Regulations (COSHH)","The Construction Design and Management Regulations (CDM)","The Work at Height Regulations governing scaffold staging"]],
["K2","What is the primary function of a Local Exhaust Ventilation (LEV) system when operating fixed woodworking machinery in a bench joinery workshop?",["To capture airborne wood dust and hazardous particles at source","To cool down high-speed electric motor windings during heavy cutting","To provide fresh ambient air circulation throughout the workshop floor","To dry out high-moisture timber boards prior to machining operations"]],
["K3","What is the primary purpose of conducting a formal toolbox talk on a carpentry site before starting a hazardous lifting operation?",["To brief the team on specific risks, control measures, and safe methods","To inspect personal hand tools for wear and sharpen dull chisel edges","To record daily attendance hours for payroll accounting purposes","To review architectural drawing revision numbers and specification notes"]],
["K4","What certification standard ensures that timber products used in construction originate from responsibly managed, sustainable forests?",["Forest Stewardship Council (FSC) or Programme for the Endorsement of Forest Certification","British Board of Agrément (BBA) product technical approval certification","International Organization for Standardization quality management standard","Construction Industry Training Board occupational competence standard"]],
["K5","What structural framing system utilizes factory-insulated composite panels made from rigid foam insulation sandwiched between structural board faces?",["Structurally Insulated Panels (SIPs) system construction","Traditional cut timber roof rafter and purlin construction","Wet trade traditional brick and block cavity wall masonry","Cold flat roof timber firring and mineral felt covering"]],
["K6","How do basic digital design and modeling systems assist architectural joiners when manufacturing complex bespoke staircases?",["By generating accurate 3D geometry, component dimensions, and CNC data","By calculating the exact site weather conditions for timber installation","By automating the manual sharpening of high-speed steel planer blades","By printing physical timber components directly using liquid adhesive"]],
["K7","Which British Standard code of practice provides guidance on the correct installation, tolerance, and performance of timber doorsets?",["British Standards governing joinery installation and building tolerances","Local municipal authority planning permission application guidelines","Commercial property insurance underwriting risk assessment manuals","Trade union collective bargaining agreement wage rate schedules"]],
["K8","When examining a joinery manufacturing drawing, what does a dashed or hidden line convention typically represent on the component view?",["Features, edges, or joints that are obscured from direct sight","The outer boundary cutting perimeter for laser-guided saws","The centerline axis of symmetry for turned timber balusters","The recommended glue line position for dowel joint insertion"]],
["K9","Which classification describes manufactured timber sheet products made by bonding together wood veneers with waterproof synthetic resin adhesives?",["Exterior grade structural plywood panels","Solid homegrown hardwood timber boards","Unseasoned softwood carcassing timber lengths","High-density fiberboard interior mouldings"]],
["K10","What are the primary environmental conditions required for dry rot fungus to germinate, grow, and destroy structural building timber?",["Elevated timber moisture content above twenty percent and poor ventilation","Continuous exposure to freezing temperatures and dry desert air conditions","Complete immersion in stagnant chemical-free freshwater storage tanks","Direct exposure to high-intensity ultraviolet sunlight through glass"]],
["K11","What category of hardware includes items such as door hinges, locks, latches, handles, and tower bolts used in joinery installations?",["Architectural ironmongery fixtures and fittings","Structural masonry restraint wall ties and anchors","Chemical anchoring resins and polyurethane foams","Flexible mastic sealant beads and glazing putty"]],
["K12","What is the first essential step in producing an accurate timber cutting list for a bespoke architectural joinery assembly project?",["Extracting finished component dimensions from working drawings and adding allowance","Ordering standard timber lengths from the local merchant without measuring","Calculating the total building floor area in square meters","Estimating the total weight of ironmongery required for the doors"]],
["K13","Why is it vital for a site carpenter to use correct technical construction terminology when discussing timber specifications with a main contractor?",["To ensure clear understanding of sizes, grades, and quality requirements","To demonstrate superior academic knowledge over other trade workers","To comply with international foreign language translation protocols","To satisfy statutory tax deduction reporting obligations on site"]],
["K14","When storing sharp hand woodworking chisels and plane irons in a toolbox drawer, what protective precaution must be taken?",["Fit protective edge guards or edge covers over the honed cutting bevels","Coat the cutting edges liberally in epoxy resin adhesive to seal them","Store them loosely in direct contact with steel hammers and squares","Submerge the metal blades in water to prevent steel corrosion"]],
["K15","What is the correct angle for the primary bevel grind when hand-grinding a standard woodworking bench chisel blade on a wet stone?",["Twenty-five degrees followed by a thirty-degree secondary micro-bevel","Exactly ninety degrees perpendicular to the parallel sides of the blade","Forty-five degrees to maximize edge impact resistance on hardwood","Ten degrees to create an extremely fragile and sharp cutting edge"]],
["K16","What is the primary benefit of manufacturing a custom wooden routing jig for batch-producing duplicate joinery components?",["Ensuring consistent accuracy, interchangeability, and speed of manufacture","Eliminating the need for any power tool safety guards during cutting","Allowing untrained personnel to operate heavy static machinery safely","Reducing the final weight of the finished timber product significantly"]],
["K17","When operating a portable electric router on site, what key safety check must be performed regarding the cutter bit before switching on?",["Ensure the cutter shank is inserted securely to the correct depth and collet is tight","Check that the motor speed is set to maximum regardless of cutter diameter","Remove the base plate dust extraction nozzle to improve line of sight","Lubricate the spinning cutting edges with heavy multi-purpose grease"]],
["K18","How does effective team working contribute to productivity on a large-scale timber frame housing construction site?",["By coordinating lifting operations and sequencing first-fix tasks efficiently","By encouraging workers to complete tasks in isolation without communication","By establishing strict hierarchical boundaries between site carpenters","By eliminating the need for formal site safety inductions and briefings"]],
["K19","What is a key benefit of fostering an inclusive and diverse culture within a site carpentry and joinery workforce?",["Enhancing team morale, communication, and collaborative problem-solving","Reducing the mandatory statutory holiday entitlement for employees","Standardizing all individual working speeds across different trades","Removing the requirement for personal protective equipment on site"]],
["K20","What action should a joiner take if they experience persistent physical musculoskeletal strain from repetitive heavy lifting in the workshop?",["Report the issue to management, assess manual handling aids, and seek advice","Ignore the physical discomfort and continue working at the same pace","Take extended unapproved leave without informing the workshop supervisor","Blame colleagues for failing to carry out all heavy material handling tasks"]],
["K21","When marking out an accurate angle for a miter joint on timber architrave, which hand tool is traditionally used alongside a marking knife?",["A sliding bevel set against a precise miter block or square","A flexible steel pocket tape measure extended to full length","A heavy masonry spirit level fitted with vertical vial tubes","A plumb bob suspended on a fine nylon marking cord"]],
["K22","When selecting timber sizes for structural floor joists using standard sizing tables, what two primary factors must be known?",["The clear span distance between supports and the imposed loading","The species of decorative timber veneer used for surface finishing","The ambient workshop air temperature and relative humidity level","The type of ironmongery and hinges specified for internal doors"]],
["K23","What is the primary purpose of span tables contained within building regulation guidance documents for domestic floor joists?",["To enable carpenters to select correct timber dimensions for structural safety","To calculate the financial cost of purchasing timber from merchants","To determine the optimum drying time for unseasoned softwood boards","To specify the correct grade of sandpaper for surface finishing work"]],
["K24","When is a scribing technique used by a site carpenter during second-fix skirting board installation?",["When fitting an internal corner joint to match an irregular wall profile","When calculating the structural span of an overhead roof purlin","When marking out dovetail joints for a workshop bench drawer","When cutting the birdsmouth notch in a traditional roof rafter"]],
["K25","What timber member in a traditional cut roof spans horizontally across the building to support the mid-span of roof rafters?",["A timber purlin supported by internal load-bearing partitions or struts","A floor joist spanning between external masonry cavity walls","A sole plate bedded down onto the concrete foundation slab","A ceiling binder running perpendicular to internal ceiling joists"]],
["K26","What is the primary difference between a warm flat roof construction and a cold flat roof construction regarding insulation placement?",["Warm roofs place insulation above the deck; cold roofs place it between joists","Warm roofs use no insulation; cold roofs use thick mineral wool batts","Warm roofs are pitched at forty-five degrees; cold roofs are flat","Warm roofs require internal plasterboard; cold roofs use timber boarding"]],
["K27","Which activity forms part of standard site carpentry first-fix operations in a new-build timber frame residential property?",["Erection of structural load-bearing stud partitions and floor joists","Hanging internal veneered fire doors and fitting architrave mouldings","Installing skirting boards, window boards, and stair handrails","Fitting kitchen base units, worktops, and stainless steel sinks"]],
["K28","Which activity falls under site carpentry second-fix installation techniques?",["Fitting door linings, architraves, skirting boards, and ironmongery","Erecting structural floor joists and load-bearing timber stud walls","Installing roof trusses, bracing members, and gable ladder frames","Fixing external wall insulation boards and breathable membranes"]],
["K29","What is the main advantage of using a rotational laser level over a traditional spirit level when setting out long runs of partition track?",["It projects a continuous 360-degree horizontal reference plane over long distances","It automatically cuts timber studwork to the required exact length","It measures the moisture content of framing timber instantaneously","It eliminates the need to wear eye protection during power tool use"]],
["K30","What critical compliance requirement applies to the manufacture and installation of architectural timber fire door assemblies?",["They must maintain certified fire resistance periods and intumescent seals","They must be manufactured exclusively from homegrown hardwood species","They must feature decorative glazed panels covering half the area","They must be hung using lightweight brass parliament hinges only"]],
["K31","What essential safety check must be carried out on a surface planer and thicknesser before feeding timber through the machine?",["Check that cutter guard and anti-kickback fingers are adjusted and functioning","Ensure the dust extraction system is switched off to reduce noise","Lubricate the wooden feed bed with heavy petroleum grease to ease sliding","Remove the outfeed table to allow rapid inspection of timber thickness"]],
["K32","Why is precision setting out on a joiner setting rod critical prior to manufacturing a bespoke timber window frame?",["Marking errors accumulate and affect component fit, squareness, and assembly","Setting rods are required by building regulations for structural warranty","It determines the exact site delivery transport vehicle dimensions","It calculates the total electrical power consumption of workshop tools"]],
["K33","Which traditional woodworking joint is renowned for its exceptional tensile strength due to interlocking fan-shaped pins and tails?",["A through-dovetail timber joint","A simple butt and screw joint","A half-lap halving timber joint","A dowelled edge-to-edge joint"]],
["K34","What is the primary purpose of incorporating a weathering rebate and a sloping sill detail into the design of a timber casement window?",["To prevent rainwater penetration and drain moisture away from the opening","To increase the thermal expansion coefficient of the glass unit","To provide a secure fixing point for internal curtain track brackets","To allow the casement sash to open outward through 180 degrees"]],
["K35","When joining solid timber boards edge-to-edge to form a wide table top, what loose-tongue wooden fastener is commonly inserted into matching slots?",["A compressed wood biscuit fastener","A threaded steel coach bolt fastener","A hardened masonry clout nail","A corrugated steel joint fastener"]],
["K36","When manufacturing a straight timber staircase in a bench joinery workshop, what component houses the ends of the treads and risers?",["The stair stringer housing members (wall string and outer string)","The handrail and intermediate baluster spindle members","The structural floor joist header framing members","The architrave and skirting board trim mouldings"]],
["K37","When manufacturing standard timber internal door frames in a joinery workshop, what timber component forms the vertical sides against which the door closes?",["The door lining jambs featuring an integral door stop planted or rebated","The architrave facing mouldings fixed around the wall opening","The skirting board trim fixed at the base of the partition","The structural studwork framing members supporting the partition"]],
["K38","What is the correct preliminary preparation required on a manufactured hardwood joinery item before applying an exterior wood stain finish?",["Thorough sanding down with progressively finer abrasives to remove machining marks","Soaking the timber in water for twenty-four hours to raise the grain permanently","Applying a thick layer of plaster primer over all exposed surfaces","Heating the wood surface with a blowtorch to draw out natural resins"]],
["K39","When mortising a mortice sash lock into the leading edge of a fire door, what tool is traditionally used to square out the rounded corners of the mortise?",["A sharp timber chisel and a mallet","A high-speed electric angle grinder","A heavy club hammer and bolster","A standard claw hammer and punch"]],
["K40","What is a key financial obligation for an individual operating as a self-employed site carpenter in the UK construction industry?",["Registering for Self Assessment with HMRC and managing own tax and National Insurance","Contributing to the employer’s statutory workplace pension scheme for staff","Collecting Value Added Tax from domestic clients regardless of turnover","Providing mandatory statutory sick pay to all independent sub-contractors"]],
["S1","What statutory check must a carpenter perform before operating a portable electric circular saw on a construction site?",["Inspect the power cable, guard operation, and blade sharpness","Measure the ambient room temperature and relative humidity","Verify the financial budget allocated for saw blade replacements","Check that the tool color matches the company safety branding"]],
["S2","When operating a woodworking bandsaw that generates significant wood dust, which safety control equipment must be engaged?",["Local exhaust ventilation extraction system and appropriate RPE","High-visibility waterproof jacket and steel toe-capped wellingtons","Heavy leather welding apron and protective welder gauntlets","Autonomous remote control switch positioned outside the workshop"]],
["S3","What is the correct procedure for handling offcuts of treated softwood timber on a sustainable construction site?",["Segregate into a designated wood recycling skip; do not burn treated wood","Burn all timber offcuts openly in a pile to clear the working area quickly","Throw treated wood offcuts into general municipal domestic waste bins","Grind the timber down into dust and wash it into surface water drains"]],
["S4","When installing internal fire doors, what regulatory standard must the finished installation comply with to satisfy building control?",["Approved Document B (Fire Safety) and relevant fire door certification","Approved Document A (Structure) load capacity calculation rules","Approved Document L (Conservation of Fuel and Power) U-value targets","Approved Document E (Resistance to the Passage of Sound) standards"]],
["S5","How should extension power cables be routed across a busy site carpentry workshop floor to prevent slip, trip, and fall hazards?",["Suspended overhead or protected by heavy-duty cable ramps on the floor","Laid loosely across main walkways so workers can step over them easily","Buried directly under uncompacted soil aggregate near doorways","Coiled tightly into loops and left unattended on active workbenches"]],
["S6","A joinery drawing specifies a component dimension of 1,250 millimeters with a manufacturing tolerance of plus or minus one millimeter. What is the minimum acceptable dimension?",["1,249 millimeters","1,248 millimeters","1,240 millimeters","1,251 millimeters"]],
["S7","When calculating timber lengths to produce a cutting list for shelving units, what percentage allowance for natural end-trimming and waste should be added?",["An additional ten percent allowance for cutting waste and trimming","A fixed contingency allowance of fifty percent across all timber types","Zero percentage allowance since theoretical lengths are exact","An additional one hundred percent allowance to cover potential errors"]],
["S8","When verbally briefing an apprentice on how to set out a timber door frame, why is it important to use correct construction terminology?",["To ensure clear understanding of components like heads, jambs, and sills","To test the apprentice on advanced academic vocabulary definitions","To comply with international foreign trade agreement documentation rules","To satisfy statutory tax deduction reporting standards on site"]],
["S9","When selecting a hand saw for cross-cutting dry softwood timber in a clean workshop, which saw type is most appropriate?",["A universal panel saw with fine cross-cut teeth for a clean finish","A coarse heavy tenon saw with large ripping teeth configuration","A flexible plasterboard jab saw with a pointed blade tip","A heavy bow saw designed for green log pruning in forestry"]],
["S10","What safety precaution is mandatory when changing the cutting bit on a portable electric router?",["Disconnect the power plug completely from the electrical supply socket","Ensure the power switch is locked in the continuous run position","Leave the machine plugged in while testing the motor rotation direction","Remove the dust extraction hose and switch on workshop lighting"]],
["S11","When hand-sharpening a bevel-edge chisel on an oilstone or waterstone, what motion ensures an even bevel profile?",["Maintain a consistent flat angle and move the blade smoothly back and forth","Rock the chisel blade back and forth rapidly to create a rounded edge","Press down heavily on the cutting tip while holding the handle elevated","Grind the steel edge at an arbitrary angle without using a guide"]],
["S12","When constructing a simple wooden shooting board jig for squaring timber ends with a hand plane, what must be precisely perpendicular?",["The fence stop relative to the path of the hand plane sole","The overall height of the jig relative to the workbench surface","The color coating of the timber material used to build the jig","The fixing screw head depth relative to the wooden base plate"]],
["S13","If a carpentry apprentice is struggling with mental health or financial stress, what support resource can they access within the industry?",["The Lighthouse Construction Industry Charity confidential helpline service","Local municipal authority parking ticket appeal adjudication boards","Commercial timber merchant loyalty reward scheme customer desks","National highway network breakdown emergency recovery teams"]],
["S14","When installing structural load-bearing timber stud partitions, how must stud members be secured to the head and sole plates?",["Nailed securely through the plates using approved structural framing nails","Attached using flexible self-adhesive tape wrapped around joints","Supported loosely in position without mechanical fixings until boarded","Secured using decorative brass wood screws inserted at forty-five degrees"]],
["S15","What type of mechanical fixing is typically specified when securing a heavy timber sole plate directly down onto a concrete foundation slab?",["Heavy-duty expanding anchor bolts or sleeve anchors","Small brass panel pins driven in with a lightweight hammer","Plastic wall plugs combined with lightweight drywall screws","Steel wire staples fired from a pneumatic staple gun"]],
["S16","When using standard timber sizing tables to determine ceiling joist dimensions for a domestic span, what does 'clear span' mean?",["The distance between the inner faces of supporting walls or partitions","The total external footprint width of the entire building structure","The diagonal distance from corner to corner of the room layout","The vertical height clearance from finished floor to ceiling joist"]],
["S17","When fixing timber architrave around a newly installed internal door frame, what joint is typically formed at the upper corners?",["A neat forty-five degree miter joint cut accurately with a saw","A ninety-degree square butt joint with exposed end grain","A half-lap halving joint glued with waterproof adhesive","A housing trench joint cut into the thickness of the architrave"]],
["S18","What timber member forms the apex of a traditional cut roof and receives the upper ends of the structural roof rafters?",["The ridge board running horizontally along the highest point of the roof","The wall plate bedded onto the external masonry cavity wall top","The ceiling joist spanning across from wall plate to wall plate","The purlin timber supporting the mid-span of the rafter length"]],
["S19","How should a cross-line laser level be stored in a site toolbox to protect its delicate internal self-leveling pendulum mechanism?",["Locked in transport mode inside a padded, impact-resistant protective case","Left switched on inside an open tool bag exposed to dust and moisture","Tossed loosely into the bottom of a general tool carrier alongside hammers","Hung vertically from a scaffold tube by its mounting clamp bracket"]],
["S20","When forming a strong structural joint in timber framing using coach screws, what preliminary hole operation is required?",["Drill a clearance hole for the shank and a pilot hole for the screw thread","Drive the screw directly into unbored timber using an impact driver","Heat the steel screw with a blowtorch before hammering it into place","Fill the joint recess with expanding foam adhesive prior to insertion"]],
["S21","When marking out a tenon for a traditional woodworking joint, which hand tool ensures lines are square across adjacent faces?",["A try square held firmly against the reference edge of the timber","A flexible steel pocket tape measure extended across the board","A heavy bricklayer plumb bob suspended on a fine nylon string","A plastic sliding bevel set to an arbitrary random angle"]],
["S22","When executing a scribing joint on a length of timber skirting board for an internal corner, what tool is used to cut along the scribed profile line?",["A fine-toothed coping saw blade held at a slight back-bevel angle","A heavy nine-inch abrasive disc cutter mounted on an angle grinder","A standard claw hammer used to split the timber along the grain","A large carpentry axe swung carefully to remove waste material"]],
["S23","When producing a full-size setting-out rod for a bespoke joinery item, what color pencil lead is traditionally used for overall dimensions?",["Black for overall dimensions and red for specific detailed machining data","Green for timber lengths and yellow for hardware ironmongery positions","Blue for internal room layouts and purple for structural floor levels","White chalk for all markings regardless of component type or size"]],
["S24","Which woodworking joint is commonly manufactured by an architectural joiner to connect a table leg to a framing rail securely?",["A mortise and tenon joint","A simple end-to-end butt joint","A corrugated fastener plate joint","A masonry expansion anchor joint"]],
["S25","When assembling a frame-and-panel cabinet door using loose biscuits, what expands upon contact with the PVA adhesive to lock the joint?",["Compressed beech wood biscuit slots absorbing moisture from the glue","Hardened steel spring pins expanding inside pre-drilled holes","Polyurethane expanding foam filling the entire internal cavity","Thermoplastic plastic dowels melting under frictional heat"]],
["S26","When manufacturing a timber casement window, what workshop machine is typically used to machine the glazing rebate and weather grooves?",["A spindle moulder fitted with profiled tungsten carbide cutter blocks","A portable electric jigsaw fitted with a narrow scrolling blade","A heavy bench-mounted crosscut saw with a coarse ripping blade","A hand-held orbital sander fitted with coarse abrasive paper"]],
["S27","When manufacturing a door frame in a joinery workshop, what component is fixed to the inside of the frame rebate to stop the door?",["A rebated or planted timber door stop moulding strip","A flexible rubber perimeter draught-proofing brush seal","A continuous strip of steel reinforcement angle iron","A decorative architrave timber facing trim profile"]],
["S28","When assembling a bespoke timber wall cabinet in the joinery workshop, how are the corner joints of the main carcass typically reinforced?",["Using glued dowels, biscuits, or pocket-hole screws concealed internally","Using large structural steel coach bolts driven through the front face","Using exposed wire nails punched beneath the wooden surface","Using heavy adhesive tape wrapped around the exterior corners"]],
["S29","When recessing a butt hinge into the edge of a timber door leaf, what tool is used to clean out the bottom and corners of the hinge mortise?",["A sharp bevel-edge chisel and a wooden mallet","A heavy pneumatic masonry breaker tool","A high-speed electric angle grinder with a sanding disc","A standard claw hammer and steel nail punch"]],
["S30","Before operating a fixed overhead thicknesser machine in the joinery workshop, what safety adjustment must the operator verify?",["That the anti-kickback fingers and dust extraction hood are securely in place","That the machine is operating at maximum feed speed without extraction","That the timber surface is coated in heavy grease to ease sliding","That the outfeed table has been removed to allow rapid component exit"]],
["B1","Which behavior demonstrates a joiner putting health, safety, and wellbeing first in a busy workshop environment?",["Refusing to operate a spindle moulder without its safety guard correctly adjusted","Removing machine guards temporarily to speed up batch production of components","Skipping personal hearing protection during noisy routing operations to save time","Working through fatigue without breaks to finish a joinery order ahead of schedule"]],
["B2","How does a joiner with a strong environmental commitment manage clean offcuts of hardwood timber in the workshop?",["Sorts and stores offcuts for smaller component reuse or local biomass recycling","Disposes of all usable hardwood offcuts into general waste skips immediately","Burns treated hardwood offcuts inside an unapproved container on site","Mixes timber waste with chemical adhesive tins for general landfill disposal"]],
["B3","What action demonstrates a positive contribution to an inclusive and diverse culture within a carpentry team?",["Treating all colleagues with equal respect and supporting collaborative working","Excluding newly appointed apprentices from team discussions and tea breaks","Making stereotypical remarks about trade backgrounds to test resilience","Working strictly in isolation to avoid interacting with other team members"]],
["B4","Which behavior indicates an ongoing commitment to seeking learning and development opportunities in joinery?",["Asking senior craftsmen to demonstrate advanced setting-out and jointing techniques","Assuming that college training covers all possible future manufacturing methods","Avoiding unfamiliar machinery tasks to prevent making errors in production","Refusing to attend manufacturer technical seminars during working hours"]],
["B5","How does a team-focused architectural joiner behave when their own manufacturing task is completed ahead of schedule?",["Offers assistance to workshop colleagues or helps tidy and maintain shared machinery areas","Ceases work early and waits in the staff canteen until official clock-out time","Criticizes colleagues who are working more slowly on their respective items","Commences unauthorized personal projects using workshop timber supplies"]]
];

EPA_QUESTIONS.siteCarpentry = JOINERY;
EPA_QUESTIONS.benchJoinery = JOINERY;
