import teachTestWorker from './worker-v2.js';

const DEFAULT_MODEL='@cf/meta/llama-3.1-8b-instruct-fast';
const WHISPER_MODEL='@cf/openai/whisper-large-v3-turbo';
const PRACTICE_TYPES=new Set(['discussion','practical']);

function clean(value,max=4000){return String(value??'').replace(/\s+/g,' ').trim().slice(0,max)}
function json(body,status=200,headers={}){return new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...headers}})}
function corsHeaders(request,env){const origin=request.headers.get('origin')||'',allowed=clean(env.ALLOWED_ORIGIN||'https://ddrnfinch.github.io',300);if(!origin)return{'access-control-allow-origin':allowed,'vary':'origin'};if(origin===allowed||origin==='http://localhost:8787'||origin==='http://127.0.0.1:8787')return{'access-control-allow-origin':origin,'vary':'origin'};return{'access-control-allow-origin':allowed,'vary':'origin'}}
function allowedOrigin(request,env){const origin=request.headers.get('origin')||'',allowed=clean(env.ALLOWED_ORIGIN||'https://ddrnfinch.github.io',300);return!origin||origin===allowed||origin==='http://localhost:8787'||origin==='http://127.0.0.1:8787'}
function sanitizeCriteria(items){if(!Array.isArray(items))return[];return items.slice(0,90).map(item=>({code:clean(item?.code||item?.id,40),label:clean(item?.label||item?.wording,700),path:clean(item?.path,700),requirement:clean(item?.requirement||item?.wording,1200)})).filter(item=>item.code||item.label||item.requirement)}
function sanitizeCourse(course={}){return{courseId:clean(course?.courseId,80),courseTitle:clean(course?.courseTitle,240),courseType:clean(course?.courseType,80),level:clean(course?.level,40),criteria:sanitizeCriteria(course?.criteria)}}
function filterMappings(values,course){const list=Array.isArray(values)?values.map(v=>clean(v,40)).filter(Boolean):[],allowed=new Set(course.criteria.map(item=>clean(item.code,40)).filter(Boolean).map(v=>v.toLowerCase()));return list.filter(value=>allowed.has(value.toLowerCase())).slice(0,4)}
function parseAiResponse(result){const value=result&&Object.prototype.hasOwnProperty.call(result,'response')?result.response:result;if(value&&typeof value==='object')return value;if(typeof value==='string')return JSON.parse(value);throw new Error('Workers AI returned an unsupported response.')}
function arrayBufferToBase64(buffer){const bytes=new Uint8Array(buffer),chunk=0x8000;let binary='';for(let i=0;i<bytes.length;i+=chunk)binary+=String.fromCharCode(...bytes.subarray(i,i+chunk));return btoa(binary)}
function parseJsonField(value,fallback){try{return JSON.parse(String(value||''))}catch{return fallback}}
function methodText(value){if(value&&typeof value==='object')return{title:clean(value.title||value.name,240),detail:clean(value.detail||value.description,900)};return{title:clean(value,240),detail:''}}

function questionSchema(){return{type:'object',properties:{question:{type:'string'},focus:{type:'string'},mappedTo:{type:'array',items:{type:'string'},maxItems:4}},required:['question','focus','mappedTo']}}
function feedbackSchema(){return{type:'object',properties:{strengths:{type:'array',items:{type:'string'},minItems:1,maxItems:3},improvements:{type:'array',items:{type:'string'},minItems:1,maxItems:3},summary:{type:'string'},followUp:{type:'string'},level:{type:'string',enum:['limited','developing','strong']},mappedTo:{type:'array',items:{type:'string'},maxItems:4}},required:['strengths','improvements','summary','followUp','level','mappedTo']}}
function contextPayload(course){return course.criteria.map(item=>({code:item.code,label:item.label,path:item.path,requirement:item.requirement}))}
function questionSystem(practiceType){const common='You create one realistic UK apprenticeship end-point-assessment practice question for Evia. Use only the supplied course criteria and assessment-method information. Never invent KSB codes or assessment rules. Do not ask for personal identifiers. Return only the requested structured JSON.';if(practiceType==='practical')return`${common} This is Practical Prep, not practical assessment. Ask one scenario-based question about planning, checks, quality, safety, tolerances, sequence or decision-making that a learner can answer verbally. Do not claim the learner has demonstrated practical competence.`;return`${common} This is interview/discussion practice. Ask one assessor-style question that requires the learner to explain, justify or give an occupational example. Keep it natural and specific enough to answer aloud.`}
function feedbackSystem(practiceType){const common='You are Evia giving coaching feedback on one spoken UK apprenticeship EPA practice answer. Judge only how completely and clearly the transcript answers the supplied question against the supplied approved course criteria. Do not make a pass/fail decision, do not award competence, do not alter learner progress, and do not infer facts the learner did not say. Return only the requested structured JSON. The level limited/developing/strong describes this practice answer only.';if(practiceType==='practical')return`${common} This is Practical Prep: focus feedback on planning, sequence, checks, safety, quality, tolerances and decision-making. Explicitly avoid claiming to have observed practical performance.`;return`${common} This is interview/discussion practice: focus feedback on explanation, justification, examples, checks and reasons. The follow-up should probe one missing or underdeveloped point.`}

async function createQuestion(body,env){const practiceType=clean(body?.practiceType).toLowerCase();if(!PRACTICE_TYPES.has(practiceType))throw new Error('Unsupported EPA practice type.');const course=sanitizeCourse(body?.course||{});if(!course.criteria.length)throw new Error('This course does not contain enough criteria for EPA practice yet.');const method=methodText(body?.assessmentMethod),previous=Array.isArray(body?.previousQuestions)?body.previousQuestions.map(v=>clean(v,800)).filter(Boolean).slice(-4):[],model=clean(env.MODEL||DEFAULT_MODEL,200)||DEFAULT_MODEL;const prompt={practiceType,course:{courseId:course.courseId,courseTitle:course.courseTitle,courseType:course.courseType,level:course.level},assessmentMethod:method,criteria:contextPayload(course),previousQuestions:previous};const result=await env.AI.run(model,{messages:[{role:'system',content:questionSystem(practiceType)},{role:'user',content:`Create one EPA practice question from this approved context only:\n${JSON.stringify(prompt)}`}],response_format:{type:'json_schema',json_schema:questionSchema()},max_tokens:450,temperature:0.4,repetition_penalty:1.08});const data=parseAiResponse(result),question=clean(data?.question,1200);if(!question)throw new Error('EPA practice AI did not return a question.');return{question,focus:clean(data?.focus,400),mappedTo:filterMappings(data?.mappedTo,course)}}

async function transcribeAudio(file,env,question){const buffer=await file.arrayBuffer();if(!buffer.byteLength)throw new Error('No audio was received.');const base64=arrayBufferToBase64(buffer);const result=await env.AI.run(WHISPER_MODEL,{audio:base64,task:'transcribe',language:'en',vad_filter:true,condition_on_previous_text:false,initial_prompt:`UK apprenticeship EPA practice response. Question: ${clean(question,500)}`});const transcript=clean(result?.text||result?.transcription_info?.text||result?.transcript,12000);if(!transcript)throw new Error('Evia could not hear enough speech to review this answer.');return transcript}
async function reviewAnswer(form,env){const practiceType=clean(form.get('practiceType')).toLowerCase();if(!PRACTICE_TYPES.has(practiceType))throw new Error('Unsupported EPA practice type.');const question=clean(form.get('question'),1200),course=sanitizeCourse(parseJsonField(form.get('course'),{})),method=methodText(parseJsonField(form.get('assessmentMethod'),{})),requestedMappings=parseJsonField(form.get('mappedTo'),[]),audio=form.get('audio');if(!question||!course.criteria.length)throw new Error('EPA practice context is incomplete.');if(!(audio instanceof File))throw new Error('Audio answer is required.');if(audio.size>12*1024*1024)throw new Error('This recording is too large. Keep EPA practice answers shorter and try again.');const transcript=await transcribeAudio(audio,env,question),model=clean(env.MODEL||DEFAULT_MODEL,200)||DEFAULT_MODEL;const prompt={practiceType,question,assessmentMethod:method,mappedTo:filterMappings(requestedMappings,course),course:{courseId:course.courseId,courseTitle:course.courseTitle},criteria:contextPayload(course),transcript};const result=await env.AI.run(model,{messages:[{role:'system',content:feedbackSystem(practiceType)},{role:'user',content:`Give coaching feedback from this approved context only:\n${JSON.stringify(prompt)}`}],response_format:{type:'json_schema',json_schema:feedbackSchema()},max_tokens:950,temperature:0.3,repetition_penalty:1.08});const data=parseAiResponse(result),strengths=Array.isArray(data?.strengths)?data.strengths.map(v=>clean(v,700)).filter(Boolean).slice(0,3):[],improvements=Array.isArray(data?.improvements)?data.improvements.map(v=>clean(v,700)).filter(Boolean).slice(0,3):[],level=['limited','developing','strong'].includes(clean(data?.level).toLowerCase())?clean(data.level).toLowerCase():'developing';if(!strengths.length)strengths.push('You gave Evia a spoken response to the question.');if(!improvements.length)improvements.push('Add one more specific reason, check or example to make the answer easier for an assessor to follow.');return{transcript,strengths,improvements,summary:clean(data?.summary,900),followUp:clean(data?.followUp,1000),level,mappedTo:filterMappings(data?.mappedTo,course)}}

async function handleEpa(request,env){const cors=corsHeaders(request,env);if(request.method==='OPTIONS')return new Response(null,{status:204,headers:{...cors,'access-control-allow-methods':'POST, OPTIONS','access-control-allow-headers':'content-type','access-control-max-age':'86400'}});if(request.method!=='POST')return json({ok:false,error:'Method not allowed.'},405,cors);if(!allowedOrigin(request,env))return json({ok:false,error:'Origin not allowed.'},403,cors);const length=Number(request.headers.get('content-length')||0);if(length>13*1024*1024)return json({ok:false,error:'Request too large.'},413,cors);try{const type=request.headers.get('content-type')||'';if(type.includes('application/json')){const body=await request.json();if(clean(body?.action).toLowerCase()!=='question')return json({ok:false,error:'Unsupported EPA practice action.'},400,cors);const result=await createQuestion(body,env);return json({ok:true,action:'question',...result},200,cors)}if(type.includes('multipart/form-data')){const form=await request.formData();if(clean(form.get('action')).toLowerCase()!=='feedback')return json({ok:false,error:'Unsupported EPA practice action.'},400,cors);const result=await reviewAnswer(form,env);return json({ok:true,action:'feedback',...result},200,cors)}return json({ok:false,error:'Unsupported content type.'},415,cors)}catch(error){return json({ok:false,error:clean(error?.message,500)||'EPA practice AI could not complete this request. Please try again.'},502,cors)}}

export default{async fetch(request,env,ctx){const url=new URL(request.url);if(url.pathname.endsWith('/v1/epa-discussion'))return handleEpa(request,env);return teachTestWorker.fetch(request,env,ctx)}};
